package model;
// Generated Jan 31, 2016 12:09:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * AllCountry generated by hbm2java
 */
@Entity
@Table(name="all_country"
    ,catalog="vxsee"
    , uniqueConstraints = @UniqueConstraint(columnNames="country_name") 
)
public class AllCountry  implements java.io.Serializable {


     private Integer countryId;
     private String countryCode;
     private String countryName;
     private short life;
     private String createbyId;
     private Date createdt;
     private String writebyId;
     private Date writedt;
     private Set<ConCompany> conCompanies = new HashSet<ConCompany>(0);
     private Set<CrmCustomer> crmCustomers = new HashSet<CrmCustomer>(0);

    public AllCountry() {
    }

	
    public AllCountry(short life) {
        this.life = life;
    }
    public AllCountry(String countryCode, String countryName, short life, String createbyId, Date createdt, String writebyId, Date writedt, Set<ConCompany> conCompanies, Set<CrmCustomer> crmCustomers) {
       this.countryCode = countryCode;
       this.countryName = countryName;
       this.life = life;
       this.createbyId = createbyId;
       this.createdt = createdt;
       this.writebyId = writebyId;
       this.writedt = writedt;
       this.conCompanies = conCompanies;
       this.crmCustomers = crmCustomers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="country_id", unique=true, nullable=false)
    public Integer getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    
    @Column(name="country_code", length=50)
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    
    @Column(name="country_name", unique=true, length=50)
    public String getCountryName() {
        return this.countryName;
    }
    
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    
    @Column(name="life", nullable=false)
    public short getLife() {
        return this.life;
    }
    
    public void setLife(short life) {
        this.life = life;
    }

    
    @Column(name="createby_id", length=100)
    public String getCreatebyId() {
        return this.createbyId;
    }
    
    public void setCreatebyId(String createbyId) {
        this.createbyId = createbyId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdt", length=19)
    public Date getCreatedt() {
        return this.createdt;
    }
    
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }

    
    @Column(name="writeby_id", length=100)
    public String getWritebyId() {
        return this.writebyId;
    }
    
    public void setWritebyId(String writebyId) {
        this.writebyId = writebyId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="writedt", length=19)
    public Date getWritedt() {
        return this.writedt;
    }
    
    public void setWritedt(Date writedt) {
        this.writedt = writedt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="allCountry")
    public Set<ConCompany> getConCompanies() {
        return this.conCompanies;
    }
    
    public void setConCompanies(Set<ConCompany> conCompanies) {
        this.conCompanies = conCompanies;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="allCountry")
    public Set<CrmCustomer> getCrmCustomers() {
        return this.crmCustomers;
    }
    
    public void setCrmCustomers(Set<CrmCustomer> crmCustomers) {
        this.crmCustomers = crmCustomers;
    }




}


