package model;
// Generated Jan 31, 2016 12:09:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CommonCombo generated by hbm2java
 */
@Entity
@Table(name="common_combo"
    ,catalog="vxsee"
)
public class CommonCombo  implements java.io.Serializable {


     private Integer comboId;
     private CommonCombo commonCombo;
     private String comboType;
     private String comboName;
     private Set<CrmCustomer> crmCustomers = new HashSet<CrmCustomer>(0);
     private Set<CommonCombo> commonCombos = new HashSet<CommonCombo>(0);

    public CommonCombo() {
    }

    public CommonCombo(CommonCombo commonCombo, String comboType, String comboName, Set<CrmCustomer> crmCustomers, Set<CommonCombo> commonCombos) {
       this.commonCombo = commonCombo;
       this.comboType = comboType;
       this.comboName = comboName;
       this.crmCustomers = crmCustomers;
       this.commonCombos = commonCombos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="combo_id", unique=true, nullable=false)
    public Integer getComboId() {
        return this.comboId;
    }
    
    public void setComboId(Integer comboId) {
        this.comboId = comboId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="parent_id")
    public CommonCombo getCommonCombo() {
        return this.commonCombo;
    }
    
    public void setCommonCombo(CommonCombo commonCombo) {
        this.commonCombo = commonCombo;
    }

    
    @Column(name="combo_type", length=50)
    public String getComboType() {
        return this.comboType;
    }
    
    public void setComboType(String comboType) {
        this.comboType = comboType;
    }

    
    @Column(name="combo_name", length=50)
    public String getComboName() {
        return this.comboName;
    }
    
    public void setComboName(String comboName) {
        this.comboName = comboName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="commonCombo")
    public Set<CrmCustomer> getCrmCustomers() {
        return this.crmCustomers;
    }
    
    public void setCrmCustomers(Set<CrmCustomer> crmCustomers) {
        this.crmCustomers = crmCustomers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="commonCombo")
    public Set<CommonCombo> getCommonCombos() {
        return this.commonCombos;
    }
    
    public void setCommonCombos(Set<CommonCombo> commonCombos) {
        this.commonCombos = commonCombos;
    }




}


