package model;
// Generated Jan 31, 2016 12:09:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConUser generated by hbm2java
 */
@Entity
@Table(name="con_user"
    ,catalog="vxsee"
)
public class ConUser  implements java.io.Serializable {


     private Integer userId;
     private ConLife conLife;
     private String surname;
     private String otherName;
     private Integer createbyId;
     private Date createdt;
     private Integer writebyId;
     private Date writedt;
     private Set<CrmUomCateg> crmUomCategsForCreatebyId = new HashSet<CrmUomCateg>(0);
     private Set<CrmUomCateg> crmUomCategsForWritebyId = new HashSet<CrmUomCateg>(0);
     private Set<ItemLevel> itemLevelsForCreatebyId = new HashSet<ItemLevel>(0);
     private Set<ItemLevel> itemLevelsForWritebyId = new HashSet<ItemLevel>(0);
     private Set<PurchaseRequisitionLine> purchaseRequisitionLinesForWritebyId = new HashSet<PurchaseRequisitionLine>(0);
     private Set<PurchaseRequisitionLine> purchaseRequisitionLinesForCreatebyId = new HashSet<PurchaseRequisitionLine>(0);
     private Set<FinVat> finVatsForWritebyId = new HashSet<FinVat>(0);
     private Set<FinVat> finVatsForCreatebyId = new HashSet<FinVat>(0);
     private Set<Issue> issuesForCreatebyId = new HashSet<Issue>(0);
     private Set<ItemDimensions> itemDimensionsesForCreatebyId = new HashSet<ItemDimensions>(0);
     private Set<ItemDimensions> itemDimensionsesForWritebyId = new HashSet<ItemDimensions>(0);
     private Set<PrcSuppliers> prcSuppliersesForWritebyId = new HashSet<PrcSuppliers>(0);
     private Set<PrcSuppliers> prcSuppliersesForCreatebyId = new HashSet<PrcSuppliers>(0);
     private Set<Issue> issuesForWritebyId = new HashSet<Issue>(0);
     private Set<PrcPurchaseOrderLine> prcPurchaseOrderLinesForCreatebyId = new HashSet<PrcPurchaseOrderLine>(0);
     private Set<Bank> banksForWritebyId = new HashSet<Bank>(0);
     private Set<Bank> banksForCreatebyId = new HashSet<Bank>(0);
     private Set<BankAccount> bankAccountsForWritebyId = new HashSet<BankAccount>(0);
     private Set<BankAccount> bankAccountsForCreatebyId = new HashSet<BankAccount>(0);
     private Set<ItemPurchase> itemPurchasesForCreatebyId = new HashSet<ItemPurchase>(0);
     private Set<InvGoodsreceivedLine> invGoodsreceivedLinesForCreatebyId = new HashSet<InvGoodsreceivedLine>(0);
     private Set<InvGoodsreceivedLine> invGoodsreceivedLinesForWritebyId = new HashSet<InvGoodsreceivedLine>(0);
     private Set<PrcPurchaseOrderLine> prcPurchaseOrderLinesForWritebyId = new HashSet<PrcPurchaseOrderLine>(0);
     private Set<ItemPurchase> itemPurchasesForWritebyId = new HashSet<ItemPurchase>(0);
     private Set<CrmCustomer> crmCustomersForCreatebyId = new HashSet<CrmCustomer>(0);
     private Set<CrmCustomer> crmCustomersForWritebyId = new HashSet<CrmCustomer>(0);
     private Set<ConAuth> conAuthsForUserId = new HashSet<ConAuth>(0);
     private Set<CrmCustomer> crmCustomersForCreatebyId_1 = new HashSet<CrmCustomer>(0);
     private Set<CrmCustomer> crmCustomersForWritebyId_1 = new HashSet<CrmCustomer>(0);
     private Set<CrmCustomer> crmCustomersForCreatebyId_2 = new HashSet<CrmCustomer>(0);
     private Set<CrmDelivery> crmDeliveriesForWritebyId = new HashSet<CrmDelivery>(0);
     private Set<CrmDelivery> crmDeliveriesForCreatebyId = new HashSet<CrmDelivery>(0);
     private Set<CrmSalesinvoice> crmSalesinvoicesForWritebyId = new HashSet<CrmSalesinvoice>(0);
     private Set<CrmCustomer> crmCustomersForWritebyId_2 = new HashSet<CrmCustomer>(0);
     private Set<CrmSalesinvoice> crmSalesinvoicesForCreatebyId = new HashSet<CrmSalesinvoice>(0);
     private Set<CrmQuote> crmQuotesForCreatebyId = new HashSet<CrmQuote>(0);
     private Set<CrmQuote> crmQuotesForWritebyId = new HashSet<CrmQuote>(0);
     private Set<InvStockcountLine> invStockcountLinesForWritebyId = new HashSet<InvStockcountLine>(0);
     private Set<ItemSale> itemSalesForWritebyId = new HashSet<ItemSale>(0);
     private Set<InvStockcountLine> invStockcountLinesForCreatebyId = new HashSet<InvStockcountLine>(0);
     private Set<ConObjectrights> conObjectrightses = new HashSet<ConObjectrights>(0);
     private Set<ItemSale> itemSalesForCreatebyId = new HashSet<ItemSale>(0);
     private Set<ConNotifications> conNotificationsesForCreatebyId = new HashSet<ConNotifications>(0);
     private Set<ConNotifications> conNotificationsesForWritebyId = new HashSet<ConNotifications>(0);
     private Set<ConIndustry> conIndustriesForWritebyId = new HashSet<ConIndustry>(0);
     private Set<CrmSalesorderLine> crmSalesorderLinesForWritebyId = new HashSet<CrmSalesorderLine>(0);
     private Set<InvStockcount> invStockcountsForCreatebyId = new HashSet<InvStockcount>(0);
     private Set<InvStockcount> invStockcountsForWritebyId = new HashSet<InvStockcount>(0);
     private Set<CrmSalesorderLine> crmSalesorderLinesForCreatebyId = new HashSet<CrmSalesorderLine>(0);
     private Set<ConAuth> conAuthsForCreatebyId = new HashSet<ConAuth>(0);
     private Set<CrmCustomer> crmCustomersForWritebyId_3 = new HashSet<CrmCustomer>(0);
     private Set<CrmCustomer> crmCustomersForCreatebyId_3 = new HashSet<CrmCustomer>(0);
     private Set<CrmCustomerCategory> crmCustomerCategoriesForWritebyId = new HashSet<CrmCustomerCategory>(0);
     private Set<CrmCustomerCategory> crmCustomerCategoriesForCreatebyId = new HashSet<CrmCustomerCategory>(0);
     private Set<ItemCustomPrices> itemCustomPricesesForWritebyId = new HashSet<ItemCustomPrices>(0);
     private Set<ItemCustomPrices> itemCustomPricesesForCreatebyId = new HashSet<ItemCustomPrices>(0);
     private Set<ConAuth> conAuthsForWritebyId = new HashSet<ConAuth>(0);
     private Set<ConCompany> conCompaniesForCreatebyId = new HashSet<ConCompany>(0);
     private Set<PrcPurchaseOrder> prcPurchaseOrdersForApprovedby = new HashSet<PrcPurchaseOrder>(0);
     private Set<Branch> branchesForWritebyId = new HashSet<Branch>(0);
     private Set<PrcPurchaseOrder> prcPurchaseOrdersForCreatebyId = new HashSet<PrcPurchaseOrder>(0);
     private Set<PrcPurchaseOrder> prcPurchaseOrdersForWritebyId = new HashSet<PrcPurchaseOrder>(0);
     private Set<CrmUom> crmUomsForCreatebyId = new HashSet<CrmUom>(0);
     private Set<CrmUom> crmUomsForWritebyId = new HashSet<CrmUom>(0);
     private Set<Branch> branchesForCreatebyId = new HashSet<Branch>(0);
     private Set<Payterm> paytermsForCreatebyId = new HashSet<Payterm>(0);
     private Set<Payterm> paytermsForWritebyId = new HashSet<Payterm>(0);
     private Set<CrmSalesorder> crmSalesordersForWritebyId = new HashSet<CrmSalesorder>(0);
     private Set<ItemColour> itemColoursForWritebyId = new HashSet<ItemColour>(0);
     private Set<ItemColour> itemColoursForCreatebyId = new HashSet<ItemColour>(0);
     private Set<ItemColour> itemColoursForCreatebyId_1 = new HashSet<ItemColour>(0);
     private Set<CrmSalesorder> crmSalesordersForCreatebyId = new HashSet<CrmSalesorder>(0);
     private Set<ItemColour> itemColoursForWritebyId_1 = new HashSet<ItemColour>(0);
     private Set<Item> itemsForCreatebyId = new HashSet<Item>(0);
     private Set<Item> itemsForWritebyId = new HashSet<Item>(0);
     private Set<ConObjects> conObjectsesForWritebyId = new HashSet<ConObjects>(0);
     private Set<ConObjects> conObjectsesForCreatebyId = new HashSet<ConObjects>(0);
     private Set<ConProfiles> conProfilesesForWritebyId = new HashSet<ConProfiles>(0);
     private Set<ConProfiles> conProfilesesForCreatebyId = new HashSet<ConProfiles>(0);
     private Set<ConIndustry> conIndustriesForCreatebyId = new HashSet<ConIndustry>(0);
     private Set<InvStore> invStoresForWritebyId = new HashSet<InvStore>(0);
     private Set<PoDtl> poDtlsForWritebyId = new HashSet<PoDtl>(0);
     private Set<InvStore> invStoresForCreatebyId = new HashSet<InvStore>(0);
     private Set<PoDtl> poDtlsForCreatebyId = new HashSet<PoDtl>(0);
     private Set<CrmQuoteLine> crmQuoteLinesForCreatebyId = new HashSet<CrmQuoteLine>(0);
     private Set<MfcJobcard> mfcJobcardsForWritebyId = new HashSet<MfcJobcard>(0);
     private Set<MfcJobcard> mfcJobcardsForCreatebyId = new HashSet<MfcJobcard>(0);
     private Set<CrmPos> crmPosesForCreatebyId = new HashSet<CrmPos>(0);
     private Set<CrmPos> crmPosesForWritebyId = new HashSet<CrmPos>(0);
     private Set<IssueLine> issueLinesForWritebyId = new HashSet<IssueLine>(0);
     private Set<IssueLine> issueLinesForCreatebyId = new HashSet<IssueLine>(0);
     private Set<ConCompany> conCompaniesForWritebyId = new HashSet<ConCompany>(0);
     private Set<Paymode> paymodesForCreatebyId = new HashSet<Paymode>(0);
     private Set<CrmQuoteLine> crmQuoteLinesForWritebyId = new HashSet<CrmQuoteLine>(0);
     private Set<Paymode> paymodesForWritebyId = new HashSet<Paymode>(0);
     private Set<PurchaseRequisition> purchaseRequisitionsForCreatebyId = new HashSet<PurchaseRequisition>(0);
     private Set<ConObjectscaption> conObjectscaptionsForCreatebyId = new HashSet<ConObjectscaption>(0);
     private Set<PurchaseRequisition> purchaseRequisitionsForWritebyId = new HashSet<PurchaseRequisition>(0);
     private Set<ConObjectscaption> conObjectscaptionsForWritebyId = new HashSet<ConObjectscaption>(0);
     private Set<ItemConfiguration> itemConfigurationsForWritebyId = new HashSet<ItemConfiguration>(0);
     private Set<ItemConfiguration> itemConfigurationsForCreatebyId = new HashSet<ItemConfiguration>(0);
     private Set<CrmDeliveryLine> crmDeliveryLinesForCreatebyId = new HashSet<CrmDeliveryLine>(0);
     private Set<CrmDeliveryLine> crmDeliveryLinesForWritebyId = new HashSet<CrmDeliveryLine>(0);
     private Set<CrmPosLine> crmPosLinesForWritebyId = new HashSet<CrmPosLine>(0);
     private Set<CrmPosLine> crmPosLinesForCreatebyId = new HashSet<CrmPosLine>(0);

    public ConUser() {
    }

	
    public ConUser(ConLife conLife) {
        this.conLife = conLife;
    }
    public ConUser(ConLife conLife, String surname, String otherName, Integer createbyId, Date createdt, Integer writebyId, Date writedt, Set<CrmUomCateg> crmUomCategsForCreatebyId, Set<CrmUomCateg> crmUomCategsForWritebyId, Set<ItemLevel> itemLevelsForCreatebyId, Set<ItemLevel> itemLevelsForWritebyId, Set<PurchaseRequisitionLine> purchaseRequisitionLinesForWritebyId, Set<PurchaseRequisitionLine> purchaseRequisitionLinesForCreatebyId, Set<FinVat> finVatsForWritebyId, Set<FinVat> finVatsForCreatebyId, Set<Issue> issuesForCreatebyId, Set<ItemDimensions> itemDimensionsesForCreatebyId, Set<ItemDimensions> itemDimensionsesForWritebyId, Set<PrcSuppliers> prcSuppliersesForWritebyId, Set<PrcSuppliers> prcSuppliersesForCreatebyId, Set<Issue> issuesForWritebyId, Set<PrcPurchaseOrderLine> prcPurchaseOrderLinesForCreatebyId, Set<Bank> banksForWritebyId, Set<Bank> banksForCreatebyId, Set<BankAccount> bankAccountsForWritebyId, Set<BankAccount> bankAccountsForCreatebyId, Set<ItemPurchase> itemPurchasesForCreatebyId, Set<InvGoodsreceivedLine> invGoodsreceivedLinesForCreatebyId, Set<InvGoodsreceivedLine> invGoodsreceivedLinesForWritebyId, Set<PrcPurchaseOrderLine> prcPurchaseOrderLinesForWritebyId, Set<ItemPurchase> itemPurchasesForWritebyId, Set<CrmCustomer> crmCustomersForCreatebyId, Set<CrmCustomer> crmCustomersForWritebyId, Set<ConAuth> conAuthsForUserId, Set<CrmCustomer> crmCustomersForCreatebyId_1, Set<CrmCustomer> crmCustomersForWritebyId_1, Set<CrmCustomer> crmCustomersForCreatebyId_2, Set<CrmDelivery> crmDeliveriesForWritebyId, Set<CrmDelivery> crmDeliveriesForCreatebyId, Set<CrmSalesinvoice> crmSalesinvoicesForWritebyId, Set<CrmCustomer> crmCustomersForWritebyId_2, Set<CrmSalesinvoice> crmSalesinvoicesForCreatebyId, Set<CrmQuote> crmQuotesForCreatebyId, Set<CrmQuote> crmQuotesForWritebyId, Set<InvStockcountLine> invStockcountLinesForWritebyId, Set<ItemSale> itemSalesForWritebyId, Set<InvStockcountLine> invStockcountLinesForCreatebyId, Set<ConObjectrights> conObjectrightses, Set<ItemSale> itemSalesForCreatebyId, Set<ConNotifications> conNotificationsesForCreatebyId, Set<ConNotifications> conNotificationsesForWritebyId, Set<ConIndustry> conIndustriesForWritebyId, Set<CrmSalesorderLine> crmSalesorderLinesForWritebyId, Set<InvStockcount> invStockcountsForCreatebyId, Set<InvStockcount> invStockcountsForWritebyId, Set<CrmSalesorderLine> crmSalesorderLinesForCreatebyId, Set<ConAuth> conAuthsForCreatebyId, Set<CrmCustomer> crmCustomersForWritebyId_3, Set<CrmCustomer> crmCustomersForCreatebyId_3, Set<CrmCustomerCategory> crmCustomerCategoriesForWritebyId, Set<CrmCustomerCategory> crmCustomerCategoriesForCreatebyId, Set<ItemCustomPrices> itemCustomPricesesForWritebyId, Set<ItemCustomPrices> itemCustomPricesesForCreatebyId, Set<ConAuth> conAuthsForWritebyId, Set<ConCompany> conCompaniesForCreatebyId, Set<PrcPurchaseOrder> prcPurchaseOrdersForApprovedby, Set<Branch> branchesForWritebyId, Set<PrcPurchaseOrder> prcPurchaseOrdersForCreatebyId, Set<PrcPurchaseOrder> prcPurchaseOrdersForWritebyId, Set<CrmUom> crmUomsForCreatebyId, Set<CrmUom> crmUomsForWritebyId, Set<Branch> branchesForCreatebyId, Set<Payterm> paytermsForCreatebyId, Set<Payterm> paytermsForWritebyId, Set<CrmSalesorder> crmSalesordersForWritebyId, Set<ItemColour> itemColoursForWritebyId, Set<ItemColour> itemColoursForCreatebyId, Set<ItemColour> itemColoursForCreatebyId_1, Set<CrmSalesorder> crmSalesordersForCreatebyId, Set<ItemColour> itemColoursForWritebyId_1, Set<Item> itemsForCreatebyId, Set<Item> itemsForWritebyId, Set<ConObjects> conObjectsesForWritebyId, Set<ConObjects> conObjectsesForCreatebyId, Set<ConProfiles> conProfilesesForWritebyId, Set<ConProfiles> conProfilesesForCreatebyId, Set<ConIndustry> conIndustriesForCreatebyId, Set<InvStore> invStoresForWritebyId, Set<PoDtl> poDtlsForWritebyId, Set<InvStore> invStoresForCreatebyId, Set<PoDtl> poDtlsForCreatebyId, Set<CrmQuoteLine> crmQuoteLinesForCreatebyId, Set<MfcJobcard> mfcJobcardsForWritebyId, Set<MfcJobcard> mfcJobcardsForCreatebyId, Set<CrmPos> crmPosesForCreatebyId, Set<CrmPos> crmPosesForWritebyId, Set<IssueLine> issueLinesForWritebyId, Set<IssueLine> issueLinesForCreatebyId, Set<ConCompany> conCompaniesForWritebyId, Set<Paymode> paymodesForCreatebyId, Set<CrmQuoteLine> crmQuoteLinesForWritebyId, Set<Paymode> paymodesForWritebyId, Set<PurchaseRequisition> purchaseRequisitionsForCreatebyId, Set<ConObjectscaption> conObjectscaptionsForCreatebyId, Set<PurchaseRequisition> purchaseRequisitionsForWritebyId, Set<ConObjectscaption> conObjectscaptionsForWritebyId, Set<ItemConfiguration> itemConfigurationsForWritebyId, Set<ItemConfiguration> itemConfigurationsForCreatebyId, Set<CrmDeliveryLine> crmDeliveryLinesForCreatebyId, Set<CrmDeliveryLine> crmDeliveryLinesForWritebyId, Set<CrmPosLine> crmPosLinesForWritebyId, Set<CrmPosLine> crmPosLinesForCreatebyId) {
       this.conLife = conLife;
       this.surname = surname;
       this.otherName = otherName;
       this.createbyId = createbyId;
       this.createdt = createdt;
       this.writebyId = writebyId;
       this.writedt = writedt;
       this.crmUomCategsForCreatebyId = crmUomCategsForCreatebyId;
       this.crmUomCategsForWritebyId = crmUomCategsForWritebyId;
       this.itemLevelsForCreatebyId = itemLevelsForCreatebyId;
       this.itemLevelsForWritebyId = itemLevelsForWritebyId;
       this.purchaseRequisitionLinesForWritebyId = purchaseRequisitionLinesForWritebyId;
       this.purchaseRequisitionLinesForCreatebyId = purchaseRequisitionLinesForCreatebyId;
       this.finVatsForWritebyId = finVatsForWritebyId;
       this.finVatsForCreatebyId = finVatsForCreatebyId;
       this.issuesForCreatebyId = issuesForCreatebyId;
       this.itemDimensionsesForCreatebyId = itemDimensionsesForCreatebyId;
       this.itemDimensionsesForWritebyId = itemDimensionsesForWritebyId;
       this.prcSuppliersesForWritebyId = prcSuppliersesForWritebyId;
       this.prcSuppliersesForCreatebyId = prcSuppliersesForCreatebyId;
       this.issuesForWritebyId = issuesForWritebyId;
       this.prcPurchaseOrderLinesForCreatebyId = prcPurchaseOrderLinesForCreatebyId;
       this.banksForWritebyId = banksForWritebyId;
       this.banksForCreatebyId = banksForCreatebyId;
       this.bankAccountsForWritebyId = bankAccountsForWritebyId;
       this.bankAccountsForCreatebyId = bankAccountsForCreatebyId;
       this.itemPurchasesForCreatebyId = itemPurchasesForCreatebyId;
       this.invGoodsreceivedLinesForCreatebyId = invGoodsreceivedLinesForCreatebyId;
       this.invGoodsreceivedLinesForWritebyId = invGoodsreceivedLinesForWritebyId;
       this.prcPurchaseOrderLinesForWritebyId = prcPurchaseOrderLinesForWritebyId;
       this.itemPurchasesForWritebyId = itemPurchasesForWritebyId;
       this.crmCustomersForCreatebyId = crmCustomersForCreatebyId;
       this.crmCustomersForWritebyId = crmCustomersForWritebyId;
       this.conAuthsForUserId = conAuthsForUserId;
       this.crmCustomersForCreatebyId_1 = crmCustomersForCreatebyId_1;
       this.crmCustomersForWritebyId_1 = crmCustomersForWritebyId_1;
       this.crmCustomersForCreatebyId_2 = crmCustomersForCreatebyId_2;
       this.crmDeliveriesForWritebyId = crmDeliveriesForWritebyId;
       this.crmDeliveriesForCreatebyId = crmDeliveriesForCreatebyId;
       this.crmSalesinvoicesForWritebyId = crmSalesinvoicesForWritebyId;
       this.crmCustomersForWritebyId_2 = crmCustomersForWritebyId_2;
       this.crmSalesinvoicesForCreatebyId = crmSalesinvoicesForCreatebyId;
       this.crmQuotesForCreatebyId = crmQuotesForCreatebyId;
       this.crmQuotesForWritebyId = crmQuotesForWritebyId;
       this.invStockcountLinesForWritebyId = invStockcountLinesForWritebyId;
       this.itemSalesForWritebyId = itemSalesForWritebyId;
       this.invStockcountLinesForCreatebyId = invStockcountLinesForCreatebyId;
       this.conObjectrightses = conObjectrightses;
       this.itemSalesForCreatebyId = itemSalesForCreatebyId;
       this.conNotificationsesForCreatebyId = conNotificationsesForCreatebyId;
       this.conNotificationsesForWritebyId = conNotificationsesForWritebyId;
       this.conIndustriesForWritebyId = conIndustriesForWritebyId;
       this.crmSalesorderLinesForWritebyId = crmSalesorderLinesForWritebyId;
       this.invStockcountsForCreatebyId = invStockcountsForCreatebyId;
       this.invStockcountsForWritebyId = invStockcountsForWritebyId;
       this.crmSalesorderLinesForCreatebyId = crmSalesorderLinesForCreatebyId;
       this.conAuthsForCreatebyId = conAuthsForCreatebyId;
       this.crmCustomersForWritebyId_3 = crmCustomersForWritebyId_3;
       this.crmCustomersForCreatebyId_3 = crmCustomersForCreatebyId_3;
       this.crmCustomerCategoriesForWritebyId = crmCustomerCategoriesForWritebyId;
       this.crmCustomerCategoriesForCreatebyId = crmCustomerCategoriesForCreatebyId;
       this.itemCustomPricesesForWritebyId = itemCustomPricesesForWritebyId;
       this.itemCustomPricesesForCreatebyId = itemCustomPricesesForCreatebyId;
       this.conAuthsForWritebyId = conAuthsForWritebyId;
       this.conCompaniesForCreatebyId = conCompaniesForCreatebyId;
       this.prcPurchaseOrdersForApprovedby = prcPurchaseOrdersForApprovedby;
       this.branchesForWritebyId = branchesForWritebyId;
       this.prcPurchaseOrdersForCreatebyId = prcPurchaseOrdersForCreatebyId;
       this.prcPurchaseOrdersForWritebyId = prcPurchaseOrdersForWritebyId;
       this.crmUomsForCreatebyId = crmUomsForCreatebyId;
       this.crmUomsForWritebyId = crmUomsForWritebyId;
       this.branchesForCreatebyId = branchesForCreatebyId;
       this.paytermsForCreatebyId = paytermsForCreatebyId;
       this.paytermsForWritebyId = paytermsForWritebyId;
       this.crmSalesordersForWritebyId = crmSalesordersForWritebyId;
       this.itemColoursForWritebyId = itemColoursForWritebyId;
       this.itemColoursForCreatebyId = itemColoursForCreatebyId;
       this.itemColoursForCreatebyId_1 = itemColoursForCreatebyId_1;
       this.crmSalesordersForCreatebyId = crmSalesordersForCreatebyId;
       this.itemColoursForWritebyId_1 = itemColoursForWritebyId_1;
       this.itemsForCreatebyId = itemsForCreatebyId;
       this.itemsForWritebyId = itemsForWritebyId;
       this.conObjectsesForWritebyId = conObjectsesForWritebyId;
       this.conObjectsesForCreatebyId = conObjectsesForCreatebyId;
       this.conProfilesesForWritebyId = conProfilesesForWritebyId;
       this.conProfilesesForCreatebyId = conProfilesesForCreatebyId;
       this.conIndustriesForCreatebyId = conIndustriesForCreatebyId;
       this.invStoresForWritebyId = invStoresForWritebyId;
       this.poDtlsForWritebyId = poDtlsForWritebyId;
       this.invStoresForCreatebyId = invStoresForCreatebyId;
       this.poDtlsForCreatebyId = poDtlsForCreatebyId;
       this.crmQuoteLinesForCreatebyId = crmQuoteLinesForCreatebyId;
       this.mfcJobcardsForWritebyId = mfcJobcardsForWritebyId;
       this.mfcJobcardsForCreatebyId = mfcJobcardsForCreatebyId;
       this.crmPosesForCreatebyId = crmPosesForCreatebyId;
       this.crmPosesForWritebyId = crmPosesForWritebyId;
       this.issueLinesForWritebyId = issueLinesForWritebyId;
       this.issueLinesForCreatebyId = issueLinesForCreatebyId;
       this.conCompaniesForWritebyId = conCompaniesForWritebyId;
       this.paymodesForCreatebyId = paymodesForCreatebyId;
       this.crmQuoteLinesForWritebyId = crmQuoteLinesForWritebyId;
       this.paymodesForWritebyId = paymodesForWritebyId;
       this.purchaseRequisitionsForCreatebyId = purchaseRequisitionsForCreatebyId;
       this.conObjectscaptionsForCreatebyId = conObjectscaptionsForCreatebyId;
       this.purchaseRequisitionsForWritebyId = purchaseRequisitionsForWritebyId;
       this.conObjectscaptionsForWritebyId = conObjectscaptionsForWritebyId;
       this.itemConfigurationsForWritebyId = itemConfigurationsForWritebyId;
       this.itemConfigurationsForCreatebyId = itemConfigurationsForCreatebyId;
       this.crmDeliveryLinesForCreatebyId = crmDeliveryLinesForCreatebyId;
       this.crmDeliveryLinesForWritebyId = crmDeliveryLinesForWritebyId;
       this.crmPosLinesForWritebyId = crmPosLinesForWritebyId;
       this.crmPosLinesForCreatebyId = crmPosLinesForCreatebyId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="user_id", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="life", nullable=false)
    public ConLife getConLife() {
        return this.conLife;
    }
    
    public void setConLife(ConLife conLife) {
        this.conLife = conLife;
    }

    
    @Column(name="surname", length=50)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="other_name", length=50)
    public String getOtherName() {
        return this.otherName;
    }
    
    public void setOtherName(String otherName) {
        this.otherName = otherName;
    }

    
    @Column(name="createby_id")
    public Integer getCreatebyId() {
        return this.createbyId;
    }
    
    public void setCreatebyId(Integer createbyId) {
        this.createbyId = createbyId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdt", length=19)
    public Date getCreatedt() {
        return this.createdt;
    }
    
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }

    
    @Column(name="writeby_id")
    public Integer getWritebyId() {
        return this.writebyId;
    }
    
    public void setWritebyId(Integer writebyId) {
        this.writebyId = writebyId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="writedt", length=19)
    public Date getWritedt() {
        return this.writedt;
    }
    
    public void setWritedt(Date writedt) {
        this.writedt = writedt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<CrmUomCateg> getCrmUomCategsForCreatebyId() {
        return this.crmUomCategsForCreatebyId;
    }
    
    public void setCrmUomCategsForCreatebyId(Set<CrmUomCateg> crmUomCategsForCreatebyId) {
        this.crmUomCategsForCreatebyId = crmUomCategsForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<CrmUomCateg> getCrmUomCategsForWritebyId() {
        return this.crmUomCategsForWritebyId;
    }
    
    public void setCrmUomCategsForWritebyId(Set<CrmUomCateg> crmUomCategsForWritebyId) {
        this.crmUomCategsForWritebyId = crmUomCategsForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<ItemLevel> getItemLevelsForCreatebyId() {
        return this.itemLevelsForCreatebyId;
    }
    
    public void setItemLevelsForCreatebyId(Set<ItemLevel> itemLevelsForCreatebyId) {
        this.itemLevelsForCreatebyId = itemLevelsForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<ItemLevel> getItemLevelsForWritebyId() {
        return this.itemLevelsForWritebyId;
    }
    
    public void setItemLevelsForWritebyId(Set<ItemLevel> itemLevelsForWritebyId) {
        this.itemLevelsForWritebyId = itemLevelsForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<PurchaseRequisitionLine> getPurchaseRequisitionLinesForWritebyId() {
        return this.purchaseRequisitionLinesForWritebyId;
    }
    
    public void setPurchaseRequisitionLinesForWritebyId(Set<PurchaseRequisitionLine> purchaseRequisitionLinesForWritebyId) {
        this.purchaseRequisitionLinesForWritebyId = purchaseRequisitionLinesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<PurchaseRequisitionLine> getPurchaseRequisitionLinesForCreatebyId() {
        return this.purchaseRequisitionLinesForCreatebyId;
    }
    
    public void setPurchaseRequisitionLinesForCreatebyId(Set<PurchaseRequisitionLine> purchaseRequisitionLinesForCreatebyId) {
        this.purchaseRequisitionLinesForCreatebyId = purchaseRequisitionLinesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<FinVat> getFinVatsForWritebyId() {
        return this.finVatsForWritebyId;
    }
    
    public void setFinVatsForWritebyId(Set<FinVat> finVatsForWritebyId) {
        this.finVatsForWritebyId = finVatsForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<FinVat> getFinVatsForCreatebyId() {
        return this.finVatsForCreatebyId;
    }
    
    public void setFinVatsForCreatebyId(Set<FinVat> finVatsForCreatebyId) {
        this.finVatsForCreatebyId = finVatsForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<Issue> getIssuesForCreatebyId() {
        return this.issuesForCreatebyId;
    }
    
    public void setIssuesForCreatebyId(Set<Issue> issuesForCreatebyId) {
        this.issuesForCreatebyId = issuesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<ItemDimensions> getItemDimensionsesForCreatebyId() {
        return this.itemDimensionsesForCreatebyId;
    }
    
    public void setItemDimensionsesForCreatebyId(Set<ItemDimensions> itemDimensionsesForCreatebyId) {
        this.itemDimensionsesForCreatebyId = itemDimensionsesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<ItemDimensions> getItemDimensionsesForWritebyId() {
        return this.itemDimensionsesForWritebyId;
    }
    
    public void setItemDimensionsesForWritebyId(Set<ItemDimensions> itemDimensionsesForWritebyId) {
        this.itemDimensionsesForWritebyId = itemDimensionsesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<PrcSuppliers> getPrcSuppliersesForWritebyId() {
        return this.prcSuppliersesForWritebyId;
    }
    
    public void setPrcSuppliersesForWritebyId(Set<PrcSuppliers> prcSuppliersesForWritebyId) {
        this.prcSuppliersesForWritebyId = prcSuppliersesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<PrcSuppliers> getPrcSuppliersesForCreatebyId() {
        return this.prcSuppliersesForCreatebyId;
    }
    
    public void setPrcSuppliersesForCreatebyId(Set<PrcSuppliers> prcSuppliersesForCreatebyId) {
        this.prcSuppliersesForCreatebyId = prcSuppliersesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<Issue> getIssuesForWritebyId() {
        return this.issuesForWritebyId;
    }
    
    public void setIssuesForWritebyId(Set<Issue> issuesForWritebyId) {
        this.issuesForWritebyId = issuesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<PrcPurchaseOrderLine> getPrcPurchaseOrderLinesForCreatebyId() {
        return this.prcPurchaseOrderLinesForCreatebyId;
    }
    
    public void setPrcPurchaseOrderLinesForCreatebyId(Set<PrcPurchaseOrderLine> prcPurchaseOrderLinesForCreatebyId) {
        this.prcPurchaseOrderLinesForCreatebyId = prcPurchaseOrderLinesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<Bank> getBanksForWritebyId() {
        return this.banksForWritebyId;
    }
    
    public void setBanksForWritebyId(Set<Bank> banksForWritebyId) {
        this.banksForWritebyId = banksForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<Bank> getBanksForCreatebyId() {
        return this.banksForCreatebyId;
    }
    
    public void setBanksForCreatebyId(Set<Bank> banksForCreatebyId) {
        this.banksForCreatebyId = banksForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<BankAccount> getBankAccountsForWritebyId() {
        return this.bankAccountsForWritebyId;
    }
    
    public void setBankAccountsForWritebyId(Set<BankAccount> bankAccountsForWritebyId) {
        this.bankAccountsForWritebyId = bankAccountsForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<BankAccount> getBankAccountsForCreatebyId() {
        return this.bankAccountsForCreatebyId;
    }
    
    public void setBankAccountsForCreatebyId(Set<BankAccount> bankAccountsForCreatebyId) {
        this.bankAccountsForCreatebyId = bankAccountsForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<ItemPurchase> getItemPurchasesForCreatebyId() {
        return this.itemPurchasesForCreatebyId;
    }
    
    public void setItemPurchasesForCreatebyId(Set<ItemPurchase> itemPurchasesForCreatebyId) {
        this.itemPurchasesForCreatebyId = itemPurchasesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<InvGoodsreceivedLine> getInvGoodsreceivedLinesForCreatebyId() {
        return this.invGoodsreceivedLinesForCreatebyId;
    }
    
    public void setInvGoodsreceivedLinesForCreatebyId(Set<InvGoodsreceivedLine> invGoodsreceivedLinesForCreatebyId) {
        this.invGoodsreceivedLinesForCreatebyId = invGoodsreceivedLinesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<InvGoodsreceivedLine> getInvGoodsreceivedLinesForWritebyId() {
        return this.invGoodsreceivedLinesForWritebyId;
    }
    
    public void setInvGoodsreceivedLinesForWritebyId(Set<InvGoodsreceivedLine> invGoodsreceivedLinesForWritebyId) {
        this.invGoodsreceivedLinesForWritebyId = invGoodsreceivedLinesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<PrcPurchaseOrderLine> getPrcPurchaseOrderLinesForWritebyId() {
        return this.prcPurchaseOrderLinesForWritebyId;
    }
    
    public void setPrcPurchaseOrderLinesForWritebyId(Set<PrcPurchaseOrderLine> prcPurchaseOrderLinesForWritebyId) {
        this.prcPurchaseOrderLinesForWritebyId = prcPurchaseOrderLinesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<ItemPurchase> getItemPurchasesForWritebyId() {
        return this.itemPurchasesForWritebyId;
    }
    
    public void setItemPurchasesForWritebyId(Set<ItemPurchase> itemPurchasesForWritebyId) {
        this.itemPurchasesForWritebyId = itemPurchasesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<CrmCustomer> getCrmCustomersForCreatebyId() {
        return this.crmCustomersForCreatebyId;
    }
    
    public void setCrmCustomersForCreatebyId(Set<CrmCustomer> crmCustomersForCreatebyId) {
        this.crmCustomersForCreatebyId = crmCustomersForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<CrmCustomer> getCrmCustomersForWritebyId() {
        return this.crmCustomersForWritebyId;
    }
    
    public void setCrmCustomersForWritebyId(Set<CrmCustomer> crmCustomersForWritebyId) {
        this.crmCustomersForWritebyId = crmCustomersForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByUserId")
    public Set<ConAuth> getConAuthsForUserId() {
        return this.conAuthsForUserId;
    }
    
    public void setConAuthsForUserId(Set<ConAuth> conAuthsForUserId) {
        this.conAuthsForUserId = conAuthsForUserId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<CrmCustomer> getCrmCustomersForCreatebyId_1() {
        return this.crmCustomersForCreatebyId_1;
    }
    
    public void setCrmCustomersForCreatebyId_1(Set<CrmCustomer> crmCustomersForCreatebyId_1) {
        this.crmCustomersForCreatebyId_1 = crmCustomersForCreatebyId_1;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<CrmCustomer> getCrmCustomersForWritebyId_1() {
        return this.crmCustomersForWritebyId_1;
    }
    
    public void setCrmCustomersForWritebyId_1(Set<CrmCustomer> crmCustomersForWritebyId_1) {
        this.crmCustomersForWritebyId_1 = crmCustomersForWritebyId_1;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<CrmCustomer> getCrmCustomersForCreatebyId_2() {
        return this.crmCustomersForCreatebyId_2;
    }
    
    public void setCrmCustomersForCreatebyId_2(Set<CrmCustomer> crmCustomersForCreatebyId_2) {
        this.crmCustomersForCreatebyId_2 = crmCustomersForCreatebyId_2;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<CrmDelivery> getCrmDeliveriesForWritebyId() {
        return this.crmDeliveriesForWritebyId;
    }
    
    public void setCrmDeliveriesForWritebyId(Set<CrmDelivery> crmDeliveriesForWritebyId) {
        this.crmDeliveriesForWritebyId = crmDeliveriesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<CrmDelivery> getCrmDeliveriesForCreatebyId() {
        return this.crmDeliveriesForCreatebyId;
    }
    
    public void setCrmDeliveriesForCreatebyId(Set<CrmDelivery> crmDeliveriesForCreatebyId) {
        this.crmDeliveriesForCreatebyId = crmDeliveriesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<CrmSalesinvoice> getCrmSalesinvoicesForWritebyId() {
        return this.crmSalesinvoicesForWritebyId;
    }
    
    public void setCrmSalesinvoicesForWritebyId(Set<CrmSalesinvoice> crmSalesinvoicesForWritebyId) {
        this.crmSalesinvoicesForWritebyId = crmSalesinvoicesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<CrmCustomer> getCrmCustomersForWritebyId_2() {
        return this.crmCustomersForWritebyId_2;
    }
    
    public void setCrmCustomersForWritebyId_2(Set<CrmCustomer> crmCustomersForWritebyId_2) {
        this.crmCustomersForWritebyId_2 = crmCustomersForWritebyId_2;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<CrmSalesinvoice> getCrmSalesinvoicesForCreatebyId() {
        return this.crmSalesinvoicesForCreatebyId;
    }
    
    public void setCrmSalesinvoicesForCreatebyId(Set<CrmSalesinvoice> crmSalesinvoicesForCreatebyId) {
        this.crmSalesinvoicesForCreatebyId = crmSalesinvoicesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<CrmQuote> getCrmQuotesForCreatebyId() {
        return this.crmQuotesForCreatebyId;
    }
    
    public void setCrmQuotesForCreatebyId(Set<CrmQuote> crmQuotesForCreatebyId) {
        this.crmQuotesForCreatebyId = crmQuotesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<CrmQuote> getCrmQuotesForWritebyId() {
        return this.crmQuotesForWritebyId;
    }
    
    public void setCrmQuotesForWritebyId(Set<CrmQuote> crmQuotesForWritebyId) {
        this.crmQuotesForWritebyId = crmQuotesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<InvStockcountLine> getInvStockcountLinesForWritebyId() {
        return this.invStockcountLinesForWritebyId;
    }
    
    public void setInvStockcountLinesForWritebyId(Set<InvStockcountLine> invStockcountLinesForWritebyId) {
        this.invStockcountLinesForWritebyId = invStockcountLinesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<ItemSale> getItemSalesForWritebyId() {
        return this.itemSalesForWritebyId;
    }
    
    public void setItemSalesForWritebyId(Set<ItemSale> itemSalesForWritebyId) {
        this.itemSalesForWritebyId = itemSalesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<InvStockcountLine> getInvStockcountLinesForCreatebyId() {
        return this.invStockcountLinesForCreatebyId;
    }
    
    public void setInvStockcountLinesForCreatebyId(Set<InvStockcountLine> invStockcountLinesForCreatebyId) {
        this.invStockcountLinesForCreatebyId = invStockcountLinesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUser")
    public Set<ConObjectrights> getConObjectrightses() {
        return this.conObjectrightses;
    }
    
    public void setConObjectrightses(Set<ConObjectrights> conObjectrightses) {
        this.conObjectrightses = conObjectrightses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<ItemSale> getItemSalesForCreatebyId() {
        return this.itemSalesForCreatebyId;
    }
    
    public void setItemSalesForCreatebyId(Set<ItemSale> itemSalesForCreatebyId) {
        this.itemSalesForCreatebyId = itemSalesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<ConNotifications> getConNotificationsesForCreatebyId() {
        return this.conNotificationsesForCreatebyId;
    }
    
    public void setConNotificationsesForCreatebyId(Set<ConNotifications> conNotificationsesForCreatebyId) {
        this.conNotificationsesForCreatebyId = conNotificationsesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<ConNotifications> getConNotificationsesForWritebyId() {
        return this.conNotificationsesForWritebyId;
    }
    
    public void setConNotificationsesForWritebyId(Set<ConNotifications> conNotificationsesForWritebyId) {
        this.conNotificationsesForWritebyId = conNotificationsesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<ConIndustry> getConIndustriesForWritebyId() {
        return this.conIndustriesForWritebyId;
    }
    
    public void setConIndustriesForWritebyId(Set<ConIndustry> conIndustriesForWritebyId) {
        this.conIndustriesForWritebyId = conIndustriesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<CrmSalesorderLine> getCrmSalesorderLinesForWritebyId() {
        return this.crmSalesorderLinesForWritebyId;
    }
    
    public void setCrmSalesorderLinesForWritebyId(Set<CrmSalesorderLine> crmSalesorderLinesForWritebyId) {
        this.crmSalesorderLinesForWritebyId = crmSalesorderLinesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<InvStockcount> getInvStockcountsForCreatebyId() {
        return this.invStockcountsForCreatebyId;
    }
    
    public void setInvStockcountsForCreatebyId(Set<InvStockcount> invStockcountsForCreatebyId) {
        this.invStockcountsForCreatebyId = invStockcountsForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<InvStockcount> getInvStockcountsForWritebyId() {
        return this.invStockcountsForWritebyId;
    }
    
    public void setInvStockcountsForWritebyId(Set<InvStockcount> invStockcountsForWritebyId) {
        this.invStockcountsForWritebyId = invStockcountsForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<CrmSalesorderLine> getCrmSalesorderLinesForCreatebyId() {
        return this.crmSalesorderLinesForCreatebyId;
    }
    
    public void setCrmSalesorderLinesForCreatebyId(Set<CrmSalesorderLine> crmSalesorderLinesForCreatebyId) {
        this.crmSalesorderLinesForCreatebyId = crmSalesorderLinesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<ConAuth> getConAuthsForCreatebyId() {
        return this.conAuthsForCreatebyId;
    }
    
    public void setConAuthsForCreatebyId(Set<ConAuth> conAuthsForCreatebyId) {
        this.conAuthsForCreatebyId = conAuthsForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<CrmCustomer> getCrmCustomersForWritebyId_3() {
        return this.crmCustomersForWritebyId_3;
    }
    
    public void setCrmCustomersForWritebyId_3(Set<CrmCustomer> crmCustomersForWritebyId_3) {
        this.crmCustomersForWritebyId_3 = crmCustomersForWritebyId_3;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<CrmCustomer> getCrmCustomersForCreatebyId_3() {
        return this.crmCustomersForCreatebyId_3;
    }
    
    public void setCrmCustomersForCreatebyId_3(Set<CrmCustomer> crmCustomersForCreatebyId_3) {
        this.crmCustomersForCreatebyId_3 = crmCustomersForCreatebyId_3;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<CrmCustomerCategory> getCrmCustomerCategoriesForWritebyId() {
        return this.crmCustomerCategoriesForWritebyId;
    }
    
    public void setCrmCustomerCategoriesForWritebyId(Set<CrmCustomerCategory> crmCustomerCategoriesForWritebyId) {
        this.crmCustomerCategoriesForWritebyId = crmCustomerCategoriesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<CrmCustomerCategory> getCrmCustomerCategoriesForCreatebyId() {
        return this.crmCustomerCategoriesForCreatebyId;
    }
    
    public void setCrmCustomerCategoriesForCreatebyId(Set<CrmCustomerCategory> crmCustomerCategoriesForCreatebyId) {
        this.crmCustomerCategoriesForCreatebyId = crmCustomerCategoriesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<ItemCustomPrices> getItemCustomPricesesForWritebyId() {
        return this.itemCustomPricesesForWritebyId;
    }
    
    public void setItemCustomPricesesForWritebyId(Set<ItemCustomPrices> itemCustomPricesesForWritebyId) {
        this.itemCustomPricesesForWritebyId = itemCustomPricesesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<ItemCustomPrices> getItemCustomPricesesForCreatebyId() {
        return this.itemCustomPricesesForCreatebyId;
    }
    
    public void setItemCustomPricesesForCreatebyId(Set<ItemCustomPrices> itemCustomPricesesForCreatebyId) {
        this.itemCustomPricesesForCreatebyId = itemCustomPricesesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<ConAuth> getConAuthsForWritebyId() {
        return this.conAuthsForWritebyId;
    }
    
    public void setConAuthsForWritebyId(Set<ConAuth> conAuthsForWritebyId) {
        this.conAuthsForWritebyId = conAuthsForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<ConCompany> getConCompaniesForCreatebyId() {
        return this.conCompaniesForCreatebyId;
    }
    
    public void setConCompaniesForCreatebyId(Set<ConCompany> conCompaniesForCreatebyId) {
        this.conCompaniesForCreatebyId = conCompaniesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByApprovedby")
    public Set<PrcPurchaseOrder> getPrcPurchaseOrdersForApprovedby() {
        return this.prcPurchaseOrdersForApprovedby;
    }
    
    public void setPrcPurchaseOrdersForApprovedby(Set<PrcPurchaseOrder> prcPurchaseOrdersForApprovedby) {
        this.prcPurchaseOrdersForApprovedby = prcPurchaseOrdersForApprovedby;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<Branch> getBranchesForWritebyId() {
        return this.branchesForWritebyId;
    }
    
    public void setBranchesForWritebyId(Set<Branch> branchesForWritebyId) {
        this.branchesForWritebyId = branchesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<PrcPurchaseOrder> getPrcPurchaseOrdersForCreatebyId() {
        return this.prcPurchaseOrdersForCreatebyId;
    }
    
    public void setPrcPurchaseOrdersForCreatebyId(Set<PrcPurchaseOrder> prcPurchaseOrdersForCreatebyId) {
        this.prcPurchaseOrdersForCreatebyId = prcPurchaseOrdersForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<PrcPurchaseOrder> getPrcPurchaseOrdersForWritebyId() {
        return this.prcPurchaseOrdersForWritebyId;
    }
    
    public void setPrcPurchaseOrdersForWritebyId(Set<PrcPurchaseOrder> prcPurchaseOrdersForWritebyId) {
        this.prcPurchaseOrdersForWritebyId = prcPurchaseOrdersForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<CrmUom> getCrmUomsForCreatebyId() {
        return this.crmUomsForCreatebyId;
    }
    
    public void setCrmUomsForCreatebyId(Set<CrmUom> crmUomsForCreatebyId) {
        this.crmUomsForCreatebyId = crmUomsForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<CrmUom> getCrmUomsForWritebyId() {
        return this.crmUomsForWritebyId;
    }
    
    public void setCrmUomsForWritebyId(Set<CrmUom> crmUomsForWritebyId) {
        this.crmUomsForWritebyId = crmUomsForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<Branch> getBranchesForCreatebyId() {
        return this.branchesForCreatebyId;
    }
    
    public void setBranchesForCreatebyId(Set<Branch> branchesForCreatebyId) {
        this.branchesForCreatebyId = branchesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<Payterm> getPaytermsForCreatebyId() {
        return this.paytermsForCreatebyId;
    }
    
    public void setPaytermsForCreatebyId(Set<Payterm> paytermsForCreatebyId) {
        this.paytermsForCreatebyId = paytermsForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<Payterm> getPaytermsForWritebyId() {
        return this.paytermsForWritebyId;
    }
    
    public void setPaytermsForWritebyId(Set<Payterm> paytermsForWritebyId) {
        this.paytermsForWritebyId = paytermsForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<CrmSalesorder> getCrmSalesordersForWritebyId() {
        return this.crmSalesordersForWritebyId;
    }
    
    public void setCrmSalesordersForWritebyId(Set<CrmSalesorder> crmSalesordersForWritebyId) {
        this.crmSalesordersForWritebyId = crmSalesordersForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<ItemColour> getItemColoursForWritebyId() {
        return this.itemColoursForWritebyId;
    }
    
    public void setItemColoursForWritebyId(Set<ItemColour> itemColoursForWritebyId) {
        this.itemColoursForWritebyId = itemColoursForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<ItemColour> getItemColoursForCreatebyId() {
        return this.itemColoursForCreatebyId;
    }
    
    public void setItemColoursForCreatebyId(Set<ItemColour> itemColoursForCreatebyId) {
        this.itemColoursForCreatebyId = itemColoursForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<ItemColour> getItemColoursForCreatebyId_1() {
        return this.itemColoursForCreatebyId_1;
    }
    
    public void setItemColoursForCreatebyId_1(Set<ItemColour> itemColoursForCreatebyId_1) {
        this.itemColoursForCreatebyId_1 = itemColoursForCreatebyId_1;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<CrmSalesorder> getCrmSalesordersForCreatebyId() {
        return this.crmSalesordersForCreatebyId;
    }
    
    public void setCrmSalesordersForCreatebyId(Set<CrmSalesorder> crmSalesordersForCreatebyId) {
        this.crmSalesordersForCreatebyId = crmSalesordersForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<ItemColour> getItemColoursForWritebyId_1() {
        return this.itemColoursForWritebyId_1;
    }
    
    public void setItemColoursForWritebyId_1(Set<ItemColour> itemColoursForWritebyId_1) {
        this.itemColoursForWritebyId_1 = itemColoursForWritebyId_1;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<Item> getItemsForCreatebyId() {
        return this.itemsForCreatebyId;
    }
    
    public void setItemsForCreatebyId(Set<Item> itemsForCreatebyId) {
        this.itemsForCreatebyId = itemsForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<Item> getItemsForWritebyId() {
        return this.itemsForWritebyId;
    }
    
    public void setItemsForWritebyId(Set<Item> itemsForWritebyId) {
        this.itemsForWritebyId = itemsForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<ConObjects> getConObjectsesForWritebyId() {
        return this.conObjectsesForWritebyId;
    }
    
    public void setConObjectsesForWritebyId(Set<ConObjects> conObjectsesForWritebyId) {
        this.conObjectsesForWritebyId = conObjectsesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<ConObjects> getConObjectsesForCreatebyId() {
        return this.conObjectsesForCreatebyId;
    }
    
    public void setConObjectsesForCreatebyId(Set<ConObjects> conObjectsesForCreatebyId) {
        this.conObjectsesForCreatebyId = conObjectsesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<ConProfiles> getConProfilesesForWritebyId() {
        return this.conProfilesesForWritebyId;
    }
    
    public void setConProfilesesForWritebyId(Set<ConProfiles> conProfilesesForWritebyId) {
        this.conProfilesesForWritebyId = conProfilesesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<ConProfiles> getConProfilesesForCreatebyId() {
        return this.conProfilesesForCreatebyId;
    }
    
    public void setConProfilesesForCreatebyId(Set<ConProfiles> conProfilesesForCreatebyId) {
        this.conProfilesesForCreatebyId = conProfilesesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<ConIndustry> getConIndustriesForCreatebyId() {
        return this.conIndustriesForCreatebyId;
    }
    
    public void setConIndustriesForCreatebyId(Set<ConIndustry> conIndustriesForCreatebyId) {
        this.conIndustriesForCreatebyId = conIndustriesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<InvStore> getInvStoresForWritebyId() {
        return this.invStoresForWritebyId;
    }
    
    public void setInvStoresForWritebyId(Set<InvStore> invStoresForWritebyId) {
        this.invStoresForWritebyId = invStoresForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<PoDtl> getPoDtlsForWritebyId() {
        return this.poDtlsForWritebyId;
    }
    
    public void setPoDtlsForWritebyId(Set<PoDtl> poDtlsForWritebyId) {
        this.poDtlsForWritebyId = poDtlsForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<InvStore> getInvStoresForCreatebyId() {
        return this.invStoresForCreatebyId;
    }
    
    public void setInvStoresForCreatebyId(Set<InvStore> invStoresForCreatebyId) {
        this.invStoresForCreatebyId = invStoresForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<PoDtl> getPoDtlsForCreatebyId() {
        return this.poDtlsForCreatebyId;
    }
    
    public void setPoDtlsForCreatebyId(Set<PoDtl> poDtlsForCreatebyId) {
        this.poDtlsForCreatebyId = poDtlsForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<CrmQuoteLine> getCrmQuoteLinesForCreatebyId() {
        return this.crmQuoteLinesForCreatebyId;
    }
    
    public void setCrmQuoteLinesForCreatebyId(Set<CrmQuoteLine> crmQuoteLinesForCreatebyId) {
        this.crmQuoteLinesForCreatebyId = crmQuoteLinesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<MfcJobcard> getMfcJobcardsForWritebyId() {
        return this.mfcJobcardsForWritebyId;
    }
    
    public void setMfcJobcardsForWritebyId(Set<MfcJobcard> mfcJobcardsForWritebyId) {
        this.mfcJobcardsForWritebyId = mfcJobcardsForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<MfcJobcard> getMfcJobcardsForCreatebyId() {
        return this.mfcJobcardsForCreatebyId;
    }
    
    public void setMfcJobcardsForCreatebyId(Set<MfcJobcard> mfcJobcardsForCreatebyId) {
        this.mfcJobcardsForCreatebyId = mfcJobcardsForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<CrmPos> getCrmPosesForCreatebyId() {
        return this.crmPosesForCreatebyId;
    }
    
    public void setCrmPosesForCreatebyId(Set<CrmPos> crmPosesForCreatebyId) {
        this.crmPosesForCreatebyId = crmPosesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<CrmPos> getCrmPosesForWritebyId() {
        return this.crmPosesForWritebyId;
    }
    
    public void setCrmPosesForWritebyId(Set<CrmPos> crmPosesForWritebyId) {
        this.crmPosesForWritebyId = crmPosesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<IssueLine> getIssueLinesForWritebyId() {
        return this.issueLinesForWritebyId;
    }
    
    public void setIssueLinesForWritebyId(Set<IssueLine> issueLinesForWritebyId) {
        this.issueLinesForWritebyId = issueLinesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<IssueLine> getIssueLinesForCreatebyId() {
        return this.issueLinesForCreatebyId;
    }
    
    public void setIssueLinesForCreatebyId(Set<IssueLine> issueLinesForCreatebyId) {
        this.issueLinesForCreatebyId = issueLinesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<ConCompany> getConCompaniesForWritebyId() {
        return this.conCompaniesForWritebyId;
    }
    
    public void setConCompaniesForWritebyId(Set<ConCompany> conCompaniesForWritebyId) {
        this.conCompaniesForWritebyId = conCompaniesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<Paymode> getPaymodesForCreatebyId() {
        return this.paymodesForCreatebyId;
    }
    
    public void setPaymodesForCreatebyId(Set<Paymode> paymodesForCreatebyId) {
        this.paymodesForCreatebyId = paymodesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<CrmQuoteLine> getCrmQuoteLinesForWritebyId() {
        return this.crmQuoteLinesForWritebyId;
    }
    
    public void setCrmQuoteLinesForWritebyId(Set<CrmQuoteLine> crmQuoteLinesForWritebyId) {
        this.crmQuoteLinesForWritebyId = crmQuoteLinesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<Paymode> getPaymodesForWritebyId() {
        return this.paymodesForWritebyId;
    }
    
    public void setPaymodesForWritebyId(Set<Paymode> paymodesForWritebyId) {
        this.paymodesForWritebyId = paymodesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<PurchaseRequisition> getPurchaseRequisitionsForCreatebyId() {
        return this.purchaseRequisitionsForCreatebyId;
    }
    
    public void setPurchaseRequisitionsForCreatebyId(Set<PurchaseRequisition> purchaseRequisitionsForCreatebyId) {
        this.purchaseRequisitionsForCreatebyId = purchaseRequisitionsForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<ConObjectscaption> getConObjectscaptionsForCreatebyId() {
        return this.conObjectscaptionsForCreatebyId;
    }
    
    public void setConObjectscaptionsForCreatebyId(Set<ConObjectscaption> conObjectscaptionsForCreatebyId) {
        this.conObjectscaptionsForCreatebyId = conObjectscaptionsForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<PurchaseRequisition> getPurchaseRequisitionsForWritebyId() {
        return this.purchaseRequisitionsForWritebyId;
    }
    
    public void setPurchaseRequisitionsForWritebyId(Set<PurchaseRequisition> purchaseRequisitionsForWritebyId) {
        this.purchaseRequisitionsForWritebyId = purchaseRequisitionsForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<ConObjectscaption> getConObjectscaptionsForWritebyId() {
        return this.conObjectscaptionsForWritebyId;
    }
    
    public void setConObjectscaptionsForWritebyId(Set<ConObjectscaption> conObjectscaptionsForWritebyId) {
        this.conObjectscaptionsForWritebyId = conObjectscaptionsForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<ItemConfiguration> getItemConfigurationsForWritebyId() {
        return this.itemConfigurationsForWritebyId;
    }
    
    public void setItemConfigurationsForWritebyId(Set<ItemConfiguration> itemConfigurationsForWritebyId) {
        this.itemConfigurationsForWritebyId = itemConfigurationsForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<ItemConfiguration> getItemConfigurationsForCreatebyId() {
        return this.itemConfigurationsForCreatebyId;
    }
    
    public void setItemConfigurationsForCreatebyId(Set<ItemConfiguration> itemConfigurationsForCreatebyId) {
        this.itemConfigurationsForCreatebyId = itemConfigurationsForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<CrmDeliveryLine> getCrmDeliveryLinesForCreatebyId() {
        return this.crmDeliveryLinesForCreatebyId;
    }
    
    public void setCrmDeliveryLinesForCreatebyId(Set<CrmDeliveryLine> crmDeliveryLinesForCreatebyId) {
        this.crmDeliveryLinesForCreatebyId = crmDeliveryLinesForCreatebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<CrmDeliveryLine> getCrmDeliveryLinesForWritebyId() {
        return this.crmDeliveryLinesForWritebyId;
    }
    
    public void setCrmDeliveryLinesForWritebyId(Set<CrmDeliveryLine> crmDeliveryLinesForWritebyId) {
        this.crmDeliveryLinesForWritebyId = crmDeliveryLinesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByWritebyId")
    public Set<CrmPosLine> getCrmPosLinesForWritebyId() {
        return this.crmPosLinesForWritebyId;
    }
    
    public void setCrmPosLinesForWritebyId(Set<CrmPosLine> crmPosLinesForWritebyId) {
        this.crmPosLinesForWritebyId = crmPosLinesForWritebyId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conUserByCreatebyId")
    public Set<CrmPosLine> getCrmPosLinesForCreatebyId() {
        return this.crmPosLinesForCreatebyId;
    }
    
    public void setCrmPosLinesForCreatebyId(Set<CrmPosLine> crmPosLinesForCreatebyId) {
        this.crmPosLinesForCreatebyId = crmPosLinesForCreatebyId;
    }




}


