package model;
// Generated Jan 31, 2016 12:09:41 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CrmSalesinvoiceLine generated by hbm2java
 */
@Entity
@Table(name="crm_salesinvoice_line"
    ,catalog="vxsee"
)
public class CrmSalesinvoiceLine  implements java.io.Serializable {


     private Integer salesinvoiceLineId;
     private Integer itemHierachyLevelId;
     private Integer productServiceId;
     private int salesorderId;
     private int salesinvoiceId;
     private BigDecimal price;
     private int qty;
     private BigDecimal discount;
     private BigDecimal interest;
     private BigDecimal percentDisc;
     private BigDecimal percentInt;
     private BigDecimal amount;
     private BigDecimal vatableAmount;
     private BigDecimal vatAmount;
     private Integer uomId;
     private BigDecimal uomQty;
     private Date qdate;
     private String memo;
     private Integer dimensionUomId;
     private BigDecimal dimensionLength;
     private BigDecimal dimensionWidth;
     private BigDecimal dimensionThickness;
     private int dimensionLengthNum;
     private int dimensionLengthDenom;
     private int dimensionWidthNum;
     private int dimensionWidthDenom;
     private String ralNo;
     private Integer life;
     private Integer createbyId;
     private Date createdt;
     private Integer writebyId;
     private Date writedt;
     private int companyId;

    public CrmSalesinvoiceLine() {
    }

	
    public CrmSalesinvoiceLine(int salesorderId, int salesinvoiceId, int qty, BigDecimal discount, BigDecimal interest, BigDecimal percentDisc, BigDecimal percentInt, BigDecimal amount, BigDecimal vatableAmount, BigDecimal vatAmount, BigDecimal uomQty, int dimensionLengthNum, int dimensionLengthDenom, int dimensionWidthNum, int dimensionWidthDenom, int companyId) {
        this.salesorderId = salesorderId;
        this.salesinvoiceId = salesinvoiceId;
        this.qty = qty;
        this.discount = discount;
        this.interest = interest;
        this.percentDisc = percentDisc;
        this.percentInt = percentInt;
        this.amount = amount;
        this.vatableAmount = vatableAmount;
        this.vatAmount = vatAmount;
        this.uomQty = uomQty;
        this.dimensionLengthNum = dimensionLengthNum;
        this.dimensionLengthDenom = dimensionLengthDenom;
        this.dimensionWidthNum = dimensionWidthNum;
        this.dimensionWidthDenom = dimensionWidthDenom;
        this.companyId = companyId;
    }
    public CrmSalesinvoiceLine(Integer itemHierachyLevelId, Integer productServiceId, int salesorderId, int salesinvoiceId, BigDecimal price, int qty, BigDecimal discount, BigDecimal interest, BigDecimal percentDisc, BigDecimal percentInt, BigDecimal amount, BigDecimal vatableAmount, BigDecimal vatAmount, Integer uomId, BigDecimal uomQty, Date qdate, String memo, Integer dimensionUomId, BigDecimal dimensionLength, BigDecimal dimensionWidth, BigDecimal dimensionThickness, int dimensionLengthNum, int dimensionLengthDenom, int dimensionWidthNum, int dimensionWidthDenom, String ralNo, Integer life, Integer createbyId, Date createdt, Integer writebyId, Date writedt, int companyId) {
       this.itemHierachyLevelId = itemHierachyLevelId;
       this.productServiceId = productServiceId;
       this.salesorderId = salesorderId;
       this.salesinvoiceId = salesinvoiceId;
       this.price = price;
       this.qty = qty;
       this.discount = discount;
       this.interest = interest;
       this.percentDisc = percentDisc;
       this.percentInt = percentInt;
       this.amount = amount;
       this.vatableAmount = vatableAmount;
       this.vatAmount = vatAmount;
       this.uomId = uomId;
       this.uomQty = uomQty;
       this.qdate = qdate;
       this.memo = memo;
       this.dimensionUomId = dimensionUomId;
       this.dimensionLength = dimensionLength;
       this.dimensionWidth = dimensionWidth;
       this.dimensionThickness = dimensionThickness;
       this.dimensionLengthNum = dimensionLengthNum;
       this.dimensionLengthDenom = dimensionLengthDenom;
       this.dimensionWidthNum = dimensionWidthNum;
       this.dimensionWidthDenom = dimensionWidthDenom;
       this.ralNo = ralNo;
       this.life = life;
       this.createbyId = createbyId;
       this.createdt = createdt;
       this.writebyId = writebyId;
       this.writedt = writedt;
       this.companyId = companyId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="salesinvoice_line_id", unique=true, nullable=false)
    public Integer getSalesinvoiceLineId() {
        return this.salesinvoiceLineId;
    }
    
    public void setSalesinvoiceLineId(Integer salesinvoiceLineId) {
        this.salesinvoiceLineId = salesinvoiceLineId;
    }

    
    @Column(name="item_hierachy_level_id")
    public Integer getItemHierachyLevelId() {
        return this.itemHierachyLevelId;
    }
    
    public void setItemHierachyLevelId(Integer itemHierachyLevelId) {
        this.itemHierachyLevelId = itemHierachyLevelId;
    }

    
    @Column(name="product_service_id")
    public Integer getProductServiceId() {
        return this.productServiceId;
    }
    
    public void setProductServiceId(Integer productServiceId) {
        this.productServiceId = productServiceId;
    }

    
    @Column(name="salesorder_id", nullable=false)
    public int getSalesorderId() {
        return this.salesorderId;
    }
    
    public void setSalesorderId(int salesorderId) {
        this.salesorderId = salesorderId;
    }

    
    @Column(name="salesinvoice_id", nullable=false)
    public int getSalesinvoiceId() {
        return this.salesinvoiceId;
    }
    
    public void setSalesinvoiceId(int salesinvoiceId) {
        this.salesinvoiceId = salesinvoiceId;
    }

    
    @Column(name="price", precision=10)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    
    @Column(name="qty", nullable=false)
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }

    
    @Column(name="discount", nullable=false, precision=10)
    public BigDecimal getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    
    @Column(name="interest", nullable=false, precision=10)
    public BigDecimal getInterest() {
        return this.interest;
    }
    
    public void setInterest(BigDecimal interest) {
        this.interest = interest;
    }

    
    @Column(name="percent_disc", nullable=false, precision=10, scale=4)
    public BigDecimal getPercentDisc() {
        return this.percentDisc;
    }
    
    public void setPercentDisc(BigDecimal percentDisc) {
        this.percentDisc = percentDisc;
    }

    
    @Column(name="percent_int", nullable=false, precision=10, scale=4)
    public BigDecimal getPercentInt() {
        return this.percentInt;
    }
    
    public void setPercentInt(BigDecimal percentInt) {
        this.percentInt = percentInt;
    }

    
    @Column(name="amount", nullable=false, precision=10)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="vatable_amount", nullable=false, precision=10)
    public BigDecimal getVatableAmount() {
        return this.vatableAmount;
    }
    
    public void setVatableAmount(BigDecimal vatableAmount) {
        this.vatableAmount = vatableAmount;
    }

    
    @Column(name="vat_amount", nullable=false, precision=10)
    public BigDecimal getVatAmount() {
        return this.vatAmount;
    }
    
    public void setVatAmount(BigDecimal vatAmount) {
        this.vatAmount = vatAmount;
    }

    
    @Column(name="uom_id")
    public Integer getUomId() {
        return this.uomId;
    }
    
    public void setUomId(Integer uomId) {
        this.uomId = uomId;
    }

    
    @Column(name="uom_qty", nullable=false, precision=10, scale=4)
    public BigDecimal getUomQty() {
        return this.uomQty;
    }
    
    public void setUomQty(BigDecimal uomQty) {
        this.uomQty = uomQty;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="qdate", length=10)
    public Date getQdate() {
        return this.qdate;
    }
    
    public void setQdate(Date qdate) {
        this.qdate = qdate;
    }

    
    @Column(name="memo", length=65535)
    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }

    
    @Column(name="dimension_uom_id")
    public Integer getDimensionUomId() {
        return this.dimensionUomId;
    }
    
    public void setDimensionUomId(Integer dimensionUomId) {
        this.dimensionUomId = dimensionUomId;
    }

    
    @Column(name="dimension_length", precision=10, scale=1)
    public BigDecimal getDimensionLength() {
        return this.dimensionLength;
    }
    
    public void setDimensionLength(BigDecimal dimensionLength) {
        this.dimensionLength = dimensionLength;
    }

    
    @Column(name="dimension_width", precision=10, scale=1)
    public BigDecimal getDimensionWidth() {
        return this.dimensionWidth;
    }
    
    public void setDimensionWidth(BigDecimal dimensionWidth) {
        this.dimensionWidth = dimensionWidth;
    }

    
    @Column(name="dimension_thickness", precision=10, scale=1)
    public BigDecimal getDimensionThickness() {
        return this.dimensionThickness;
    }
    
    public void setDimensionThickness(BigDecimal dimensionThickness) {
        this.dimensionThickness = dimensionThickness;
    }

    
    @Column(name="dimension_length_num", nullable=false)
    public int getDimensionLengthNum() {
        return this.dimensionLengthNum;
    }
    
    public void setDimensionLengthNum(int dimensionLengthNum) {
        this.dimensionLengthNum = dimensionLengthNum;
    }

    
    @Column(name="dimension_length_denom", nullable=false)
    public int getDimensionLengthDenom() {
        return this.dimensionLengthDenom;
    }
    
    public void setDimensionLengthDenom(int dimensionLengthDenom) {
        this.dimensionLengthDenom = dimensionLengthDenom;
    }

    
    @Column(name="dimension_width_num", nullable=false)
    public int getDimensionWidthNum() {
        return this.dimensionWidthNum;
    }
    
    public void setDimensionWidthNum(int dimensionWidthNum) {
        this.dimensionWidthNum = dimensionWidthNum;
    }

    
    @Column(name="dimension_width_denom", nullable=false)
    public int getDimensionWidthDenom() {
        return this.dimensionWidthDenom;
    }
    
    public void setDimensionWidthDenom(int dimensionWidthDenom) {
        this.dimensionWidthDenom = dimensionWidthDenom;
    }

    
    @Column(name="ral_no", length=50)
    public String getRalNo() {
        return this.ralNo;
    }
    
    public void setRalNo(String ralNo) {
        this.ralNo = ralNo;
    }

    
    @Column(name="life")
    public Integer getLife() {
        return this.life;
    }
    
    public void setLife(Integer life) {
        this.life = life;
    }

    
    @Column(name="createby_id")
    public Integer getCreatebyId() {
        return this.createbyId;
    }
    
    public void setCreatebyId(Integer createbyId) {
        this.createbyId = createbyId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdt", length=19)
    public Date getCreatedt() {
        return this.createdt;
    }
    
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }

    
    @Column(name="writeby_id")
    public Integer getWritebyId() {
        return this.writebyId;
    }
    
    public void setWritebyId(Integer writebyId) {
        this.writebyId = writebyId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="writedt", length=19)
    public Date getWritedt() {
        return this.writedt;
    }
    
    public void setWritedt(Date writedt) {
        this.writedt = writedt;
    }

    
    @Column(name="company_id", nullable=false)
    public int getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }




}


