package model;
// Generated Jan 31, 2016 12:09:41 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MfcJobcardLine generated by hbm2java
 */
@Entity
@Table(name="mfc_jobcard_line"
    ,catalog="vxsee"
)
public class MfcJobcardLine  implements java.io.Serializable {


     private Integer jobcardLineId;
     private int jobcardId;
     private int quoteId;
     private Integer itemHierachyLevelId;
     private Integer productServiceId;
     private int qty;
     private Integer uomId;
     private BigDecimal uomQty;
     private Date qdate;
     private String memo;
     private Integer dimensionUomId;
     private BigDecimal dimensionLength;
     private BigDecimal dimensionWidth;
     private BigDecimal dimensionThickness;
     private BigDecimal dimensionLengthNum;
     private BigDecimal dimensionLengthDenom;
     private BigDecimal dimensionWidthNum;
     private BigDecimal dimensionWidthDenom;
     private String ralNo;
     private Integer life;
     private Integer createbyId;
     private Date createdt;
     private Integer writebyId;
     private Date writedt;
     private Integer companyId;

    public MfcJobcardLine() {
    }

	
    public MfcJobcardLine(int jobcardId, int quoteId, int qty, BigDecimal uomQty, BigDecimal dimensionLengthNum, BigDecimal dimensionLengthDenom, BigDecimal dimensionWidthNum, BigDecimal dimensionWidthDenom) {
        this.jobcardId = jobcardId;
        this.quoteId = quoteId;
        this.qty = qty;
        this.uomQty = uomQty;
        this.dimensionLengthNum = dimensionLengthNum;
        this.dimensionLengthDenom = dimensionLengthDenom;
        this.dimensionWidthNum = dimensionWidthNum;
        this.dimensionWidthDenom = dimensionWidthDenom;
    }
    public MfcJobcardLine(int jobcardId, int quoteId, Integer itemHierachyLevelId, Integer productServiceId, int qty, Integer uomId, BigDecimal uomQty, Date qdate, String memo, Integer dimensionUomId, BigDecimal dimensionLength, BigDecimal dimensionWidth, BigDecimal dimensionThickness, BigDecimal dimensionLengthNum, BigDecimal dimensionLengthDenom, BigDecimal dimensionWidthNum, BigDecimal dimensionWidthDenom, String ralNo, Integer life, Integer createbyId, Date createdt, Integer writebyId, Date writedt, Integer companyId) {
       this.jobcardId = jobcardId;
       this.quoteId = quoteId;
       this.itemHierachyLevelId = itemHierachyLevelId;
       this.productServiceId = productServiceId;
       this.qty = qty;
       this.uomId = uomId;
       this.uomQty = uomQty;
       this.qdate = qdate;
       this.memo = memo;
       this.dimensionUomId = dimensionUomId;
       this.dimensionLength = dimensionLength;
       this.dimensionWidth = dimensionWidth;
       this.dimensionThickness = dimensionThickness;
       this.dimensionLengthNum = dimensionLengthNum;
       this.dimensionLengthDenom = dimensionLengthDenom;
       this.dimensionWidthNum = dimensionWidthNum;
       this.dimensionWidthDenom = dimensionWidthDenom;
       this.ralNo = ralNo;
       this.life = life;
       this.createbyId = createbyId;
       this.createdt = createdt;
       this.writebyId = writebyId;
       this.writedt = writedt;
       this.companyId = companyId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="jobcard_line_id", unique=true, nullable=false)
    public Integer getJobcardLineId() {
        return this.jobcardLineId;
    }
    
    public void setJobcardLineId(Integer jobcardLineId) {
        this.jobcardLineId = jobcardLineId;
    }

    
    @Column(name="jobcard_id", nullable=false)
    public int getJobcardId() {
        return this.jobcardId;
    }
    
    public void setJobcardId(int jobcardId) {
        this.jobcardId = jobcardId;
    }

    
    @Column(name="quote_id", nullable=false)
    public int getQuoteId() {
        return this.quoteId;
    }
    
    public void setQuoteId(int quoteId) {
        this.quoteId = quoteId;
    }

    
    @Column(name="item_hierachy_level_id")
    public Integer getItemHierachyLevelId() {
        return this.itemHierachyLevelId;
    }
    
    public void setItemHierachyLevelId(Integer itemHierachyLevelId) {
        this.itemHierachyLevelId = itemHierachyLevelId;
    }

    
    @Column(name="product_service_id")
    public Integer getProductServiceId() {
        return this.productServiceId;
    }
    
    public void setProductServiceId(Integer productServiceId) {
        this.productServiceId = productServiceId;
    }

    
    @Column(name="qty", nullable=false)
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }

    
    @Column(name="uom_id")
    public Integer getUomId() {
        return this.uomId;
    }
    
    public void setUomId(Integer uomId) {
        this.uomId = uomId;
    }

    
    @Column(name="uom_qty", nullable=false, precision=10, scale=4)
    public BigDecimal getUomQty() {
        return this.uomQty;
    }
    
    public void setUomQty(BigDecimal uomQty) {
        this.uomQty = uomQty;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="qdate", length=10)
    public Date getQdate() {
        return this.qdate;
    }
    
    public void setQdate(Date qdate) {
        this.qdate = qdate;
    }

    
    @Column(name="memo", length=65535)
    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }

    
    @Column(name="dimension_uom_id")
    public Integer getDimensionUomId() {
        return this.dimensionUomId;
    }
    
    public void setDimensionUomId(Integer dimensionUomId) {
        this.dimensionUomId = dimensionUomId;
    }

    
    @Column(name="dimension_length", precision=10, scale=1)
    public BigDecimal getDimensionLength() {
        return this.dimensionLength;
    }
    
    public void setDimensionLength(BigDecimal dimensionLength) {
        this.dimensionLength = dimensionLength;
    }

    
    @Column(name="dimension_width", precision=10, scale=1)
    public BigDecimal getDimensionWidth() {
        return this.dimensionWidth;
    }
    
    public void setDimensionWidth(BigDecimal dimensionWidth) {
        this.dimensionWidth = dimensionWidth;
    }

    
    @Column(name="dimension_thickness", precision=10, scale=1)
    public BigDecimal getDimensionThickness() {
        return this.dimensionThickness;
    }
    
    public void setDimensionThickness(BigDecimal dimensionThickness) {
        this.dimensionThickness = dimensionThickness;
    }

    
    @Column(name="dimension_length_num", nullable=false, precision=10, scale=1)
    public BigDecimal getDimensionLengthNum() {
        return this.dimensionLengthNum;
    }
    
    public void setDimensionLengthNum(BigDecimal dimensionLengthNum) {
        this.dimensionLengthNum = dimensionLengthNum;
    }

    
    @Column(name="dimension_length_denom", nullable=false, precision=10, scale=1)
    public BigDecimal getDimensionLengthDenom() {
        return this.dimensionLengthDenom;
    }
    
    public void setDimensionLengthDenom(BigDecimal dimensionLengthDenom) {
        this.dimensionLengthDenom = dimensionLengthDenom;
    }

    
    @Column(name="dimension_width_num", nullable=false, precision=10, scale=1)
    public BigDecimal getDimensionWidthNum() {
        return this.dimensionWidthNum;
    }
    
    public void setDimensionWidthNum(BigDecimal dimensionWidthNum) {
        this.dimensionWidthNum = dimensionWidthNum;
    }

    
    @Column(name="dimension_width_denom", nullable=false, precision=10, scale=1)
    public BigDecimal getDimensionWidthDenom() {
        return this.dimensionWidthDenom;
    }
    
    public void setDimensionWidthDenom(BigDecimal dimensionWidthDenom) {
        this.dimensionWidthDenom = dimensionWidthDenom;
    }

    
    @Column(name="ral_no", length=50)
    public String getRalNo() {
        return this.ralNo;
    }
    
    public void setRalNo(String ralNo) {
        this.ralNo = ralNo;
    }

    
    @Column(name="life")
    public Integer getLife() {
        return this.life;
    }
    
    public void setLife(Integer life) {
        this.life = life;
    }

    
    @Column(name="createby_id")
    public Integer getCreatebyId() {
        return this.createbyId;
    }
    
    public void setCreatebyId(Integer createbyId) {
        this.createbyId = createbyId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdt", length=19)
    public Date getCreatedt() {
        return this.createdt;
    }
    
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }

    
    @Column(name="writeby_id")
    public Integer getWritebyId() {
        return this.writebyId;
    }
    
    public void setWritebyId(Integer writebyId) {
        this.writebyId = writebyId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="writedt", length=19)
    public Date getWritedt() {
        return this.writedt;
    }
    
    public void setWritedt(Date writedt) {
        this.writedt = writedt;
    }

    
    @Column(name="company_id")
    public Integer getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }




}


