package model;
// Generated Jan 31, 2016 12:09:41 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Receipt generated by hbm2java
 */
@Entity
@Table(name="receipt"
    ,catalog="vxsee"
)
public class Receipt  implements java.io.Serializable {


     private Integer receiptId;
     private String receiptNo;
     private String receiptType;
     private String customerId;
     private String ref;
     private Date receiptDate;
     private BigDecimal amount;
     private BigDecimal discount;
     private Integer bankId;
     private String branch;
     private int cr;
     private int dr;
     private int supplierId;
     private String payer;
     private Integer productId;
     private String rctMemo;
     private boolean posted;
     private Date postDate;
     private boolean paid;
     private int seq;

    public Receipt() {
    }

	
    public Receipt(Date receiptDate, BigDecimal discount, int cr, int dr, int supplierId, boolean posted, Date postDate, boolean paid, int seq) {
        this.receiptDate = receiptDate;
        this.discount = discount;
        this.cr = cr;
        this.dr = dr;
        this.supplierId = supplierId;
        this.posted = posted;
        this.postDate = postDate;
        this.paid = paid;
        this.seq = seq;
    }
    public Receipt(String receiptNo, String receiptType, String customerId, String ref, Date receiptDate, BigDecimal amount, BigDecimal discount, Integer bankId, String branch, int cr, int dr, int supplierId, String payer, Integer productId, String rctMemo, boolean posted, Date postDate, boolean paid, int seq) {
       this.receiptNo = receiptNo;
       this.receiptType = receiptType;
       this.customerId = customerId;
       this.ref = ref;
       this.receiptDate = receiptDate;
       this.amount = amount;
       this.discount = discount;
       this.bankId = bankId;
       this.branch = branch;
       this.cr = cr;
       this.dr = dr;
       this.supplierId = supplierId;
       this.payer = payer;
       this.productId = productId;
       this.rctMemo = rctMemo;
       this.posted = posted;
       this.postDate = postDate;
       this.paid = paid;
       this.seq = seq;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="receipt_id", unique=true, nullable=false)
    public Integer getReceiptId() {
        return this.receiptId;
    }
    
    public void setReceiptId(Integer receiptId) {
        this.receiptId = receiptId;
    }

    
    @Column(name="receipt_no", length=20)
    public String getReceiptNo() {
        return this.receiptNo;
    }
    
    public void setReceiptNo(String receiptNo) {
        this.receiptNo = receiptNo;
    }

    
    @Column(name="receipt_type", length=2)
    public String getReceiptType() {
        return this.receiptType;
    }
    
    public void setReceiptType(String receiptType) {
        this.receiptType = receiptType;
    }

    
    @Column(name="customer_id")
    public String getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="ref")
    public String getRef() {
        return this.ref;
    }
    
    public void setRef(String ref) {
        this.ref = ref;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="receipt_date", nullable=false, length=10)
    public Date getReceiptDate() {
        return this.receiptDate;
    }
    
    public void setReceiptDate(Date receiptDate) {
        this.receiptDate = receiptDate;
    }

    
    @Column(name="amount", precision=10)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="discount", nullable=false, precision=10)
    public BigDecimal getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    
    @Column(name="bank_id")
    public Integer getBankId() {
        return this.bankId;
    }
    
    public void setBankId(Integer bankId) {
        this.bankId = bankId;
    }

    
    @Column(name="branch", length=100)
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }

    
    @Column(name="cr", nullable=false)
    public int getCr() {
        return this.cr;
    }
    
    public void setCr(int cr) {
        this.cr = cr;
    }

    
    @Column(name="dr", nullable=false)
    public int getDr() {
        return this.dr;
    }
    
    public void setDr(int dr) {
        this.dr = dr;
    }

    
    @Column(name="supplier_id", nullable=false)
    public int getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(int supplierId) {
        this.supplierId = supplierId;
    }

    
    @Column(name="payer", length=200)
    public String getPayer() {
        return this.payer;
    }
    
    public void setPayer(String payer) {
        this.payer = payer;
    }

    
    @Column(name="product_id")
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    
    @Column(name="rct_memo", length=65535)
    public String getRctMemo() {
        return this.rctMemo;
    }
    
    public void setRctMemo(String rctMemo) {
        this.rctMemo = rctMemo;
    }

    
    @Column(name="posted", nullable=false)
    public boolean isPosted() {
        return this.posted;
    }
    
    public void setPosted(boolean posted) {
        this.posted = posted;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="post_date", nullable=false, length=10)
    public Date getPostDate() {
        return this.postDate;
    }
    
    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }

    
    @Column(name="paid", nullable=false)
    public boolean isPaid() {
        return this.paid;
    }
    
    public void setPaid(boolean paid) {
        this.paid = paid;
    }

    
    @Column(name="seq", nullable=false)
    public int getSeq() {
        return this.seq;
    }
    
    public void setSeq(int seq) {
        this.seq = seq;
    }




}


