package model;
// Generated Jan 31, 2016 12:09:41 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ReceiptDtl generated by hbm2java
 */
@Entity
@Table(name="receipt_dtl"
    ,catalog="vxsee"
)
public class ReceiptDtl  implements java.io.Serializable {


     private Integer receiptLineId;
     private Integer receiptId;
     private BigDecimal amount;
     private int cr;
     private String paymodeId;
     private String memo;

    public ReceiptDtl() {
    }

	
    public ReceiptDtl(BigDecimal amount, int cr) {
        this.amount = amount;
        this.cr = cr;
    }
    public ReceiptDtl(Integer receiptId, BigDecimal amount, int cr, String paymodeId, String memo) {
       this.receiptId = receiptId;
       this.amount = amount;
       this.cr = cr;
       this.paymodeId = paymodeId;
       this.memo = memo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="receipt_line_id", unique=true, nullable=false)
    public Integer getReceiptLineId() {
        return this.receiptLineId;
    }
    
    public void setReceiptLineId(Integer receiptLineId) {
        this.receiptLineId = receiptLineId;
    }

    
    @Column(name="receipt_id")
    public Integer getReceiptId() {
        return this.receiptId;
    }
    
    public void setReceiptId(Integer receiptId) {
        this.receiptId = receiptId;
    }

    
    @Column(name="amount", nullable=false, precision=10)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="cr", nullable=false)
    public int getCr() {
        return this.cr;
    }
    
    public void setCr(int cr) {
        this.cr = cr;
    }

    
    @Column(name="paymode_id", length=5)
    public String getPaymodeId() {
        return this.paymodeId;
    }
    
    public void setPaymodeId(String paymodeId) {
        this.paymodeId = paymodeId;
    }

    
    @Column(name="memo", length=65535)
    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }




}


