<%-- 
    Document   : pos
    Created on : Nov 17, 2015, 5:33:23 PM
    Author     : carol
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@include  file="../../../../view/helper.jsp" %>
<%@include  file="../../../../viewcontroller/com/com/crm/poscontroller.jsp" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
            <title>Point of Sale</title>
    </head>
    <body>
        <script>
// 1.Creation of the main Layouts
            var posmainLayout = new dhtmlXLayoutObject({
                parent: "comcomcrmpos",
                pattern: "1C",
                skin: "dhx_web",
                cells: [{id: "a", text: ""}]
            });
            //create the main layout tabs 
            posmainTabbar = posmainLayout.cells("a").attachTabbar();
            // window.mainposTabbar=posmainTabbar;
            var posid = "posdetails";
            var poscaption = "P.O.S Details";
            var salesid = "saledetails";
            var salecaption = "Sale Details";
            var salesviewid = "salesviewdetails";
            var salesviewcaption = "Sales View";
            posmainTabbar.addTab(salesviewid, salesviewcaption, ((salesviewcaption.length * 5) + 70), null, false, false);
            posmainTabbar.addTab(posid, poscaption, ((poscaption.length * 5) + 70), null, true, false);
            posmainTabbar.addTab(salesid, salecaption, ((salecaption.length * 5) + 70), null, false, false);
            posmainTabbar.setSkin("dhx_terrace");
//create the pos view layout and grid
            var posdetailsGrid = posmainTabbar.cells(salesviewid).attachGrid("dhx_web");
            /***************************END ATTACHING THE OBJECTS TO THE LAYOUTS************/
            var credentialsToolbar = posmainTabbar.cells(salesviewid).attachToolbar({
                icons_path: "./icons/toolbar/icons_terrace/",
                xml: "./viewmodel/toolbar/com/com/all/basic.jsp",
                skin: "dhx_terrace"
            });
//var loadPath="out/grid/mfc/com/salesquote.php";
            posdetailsGrid.setImagePath("config/mcsk_skin/imgs/");
            posdetailsGrid.setColTypes("ro,ro,ro,ro,ro,ro,ro");
            posdetailsGrid.setHeader("#,Quote Number,Amount,Customer,Date,Status,Generated By");
            posdetailsGrid.setColAlign("left,left,left,left,left,left,left");
            posdetailsGrid.setInitWidthsP("5,15,15,*,13,13,18");
            posdetailsGrid.attachHeader(",#text_filter,#text_filter,#text_filter,#text_filter,#combo_filter,#text_filter");
            posdetailsGrid.setColSorting("int,str,str,str,str,str,str");
            posdetailsGrid.init();
            //quotedetailsGrid.load(loadPath,"json");


//            /* C ***********SETTING OBJECTS PROPERTIES***********************************/

//create the pos tabbar layout
            posLayout = new dhtmlXLayoutObject({
                parent: posmainTabbar.cells(posid),
                pattern: "3W",
                skin: "dhx_web",
                cells: [{id: "a", text: ""}]
            });
            salesLayout = new dhtmlXLayoutObject({
                parent: posmainTabbar.cells(salesid),
                pattern: "2U",
                skin: "dhx_web",
                cells: [{id: "a", text: ""}]
            });
            //1.Setting  Layouts properties


            posLayout.cells("a").hideHeader();
            posLayout.cells("b").hideHeader();
            posLayout.cells("a").setWidth(300);
            posLayout.cells("c").setWidth(300);
            posLayout.cells("c").hideArrow();
            posLayout.cells("c").setText("Product Prices");
            salesLayout.cells("a").hideHeader();
            salesLayout.cells("a").setWidth(300);
            salesLayout.cells("b").hideHeader();
            /**********************END LAYOUT MANIPULATIONS**************************/
//attach objects to the layout
            productclassview = posLayout.cells("a").attachDataView({
                type: {
                    template: "<div id='container' style='overflow-y: hidden;'><table><tr align='center' ><td padding=5  > <img src='./icons/dataview/#producticon#'  width='100' height='80' /></td></tr><tr><td><b> #productclass#</b></td></table></div>",
                    height: 115,
                    width: 110,
                    columns: 2
                },
            });
            pricechartview = posLayout.cells("c").attachDataView({
                type: {
                    template: "<div id='container' style='overflow-y: hidden;'><table><tr align='center' ><td padding=5  > #uomname#</td></tr><tr><td><b> #uomcount#</b></td></table></div>",
                    height: 40,
                    width: 110,
                    columns: 2

                },
            });
            categoryTabbar = posLayout.cells("b").attachTabbar();
            var categoryid = "categorydetails";
            var categorycaption = "Category Details";
            var productid = "productdetails";
            var productcaption = "Product Details";
            categoryTabbar.addTab(categoryid, categorycaption, ((categorycaption.length * 5) + 70), null, true, false);
            categoryTabbar.addTab(productid, productcaption, ((productcaption.length * 5) + 70), null, false, false);
            categoryTabbar.setSkin("dhx_terrace");
            /* B **************************ATTACHING THE OBJECTS TO THE LAYOUTS************/
            //ATTACH THE DATAVIEWS FOR THE LAYOUT

            productsview = categoryTabbar.cells(productid).attachDataView({
                type: {
                    template: "<div id='container' style='overflow-y: hidden;'><table><tr align='center' ><td padding=5  > #productname#</td></tr><tr><td><b> #productcode#</b></td></table></div>",
                    height: 60,
                    width: 110,
                    columns: 2
                },
            });
////ATTACH A TOOLBAR TO THE POS LAYOUT CELL A THAT WILL IS USED TO SELECT THE CLASS OF PRODUCTS WE ARE DEALING WITH
            var posToolbar = categoryTabbar.cells(categoryid).attachToolbar({
                icons_path: "./icons/toolbar/icons_terrace/",
                xml: "./viewmodel/toolbar/com/com/crm/posproductcategory.jsp",
                skin: "dhx_terrace"
            });
//            //SET THE TOOLBAR ON CLICK EVENTS
//        quoteToolbar.attachEvent("onClick", function (id) {
//            var productclasskey = id;
//            quoteGrid.clearAll();
//            quoteGrid.load('out/grid/mfc/com/posproductscategory.php?rkey=' + productclasskey, 'json');
//
//        });

            // LOAD THE PRODUCT CATEGORY GRID WITH THE DEFAULT VALUE BEING THE INITIALLY SELECTED CATEGORY
            var categoryGrid = categoryTabbar.cells(categoryid).attachGrid("dhx_web");
            categoryGrid.setImagePath("config/mcsk_skin/imgs/");
            categoryGrid.setColTypes("ro,ro,ro,ro");
            categoryGrid.setHeader("#,Product Category,Class,Count");
            categoryGrid.setColAlign("left,left,left,center");
            categoryGrid.setInitWidthsP("10,45,*,15");
            categoryGrid.attachHeader(",#text_filter,#combo_filter,");
            categoryGrid.setColSorting("int,str,str,int");
            categoryGrid.init();
            // categoryGrid.load('viewmodel/grid/com/com/crm/posproductcategory.jsp', 'json');

//grid events
            categoryGrid.attachEvent("onXLS", function () {
                categoryTabbar.cells(categoryid).progressOn();
            });
            categoryGrid.attachEvent("onXLE", function () {
                categoryTabbar.cells(categoryid).progressOff();
            });
            //  rId=-1;
            categoryGrid.attachEvent("onRowSelect", function (rId, cInd) {
                var productCategory = rId;
                productsview.clearAll();
                productsview.attachEvent("onXLS", function () {
                    categoryTabbar.cells(productid).progressOn();
                    categoryTabbar.cells(productid).setActive();

                });
                productsview.attachEvent("onXLE", function () {
                    categoryTabbar.cells(productid).progressOff();
                });
                productsview.load("viewmodel/dataview/com/com/crm/products.jsp?productCategory=" + productCategory, "json");
                // alert(productCategory);
                productsview.attachEvent("onItemClick", function (id, ev, html) {

                    var pcategory = categoryGrid.cells(rId, 1).getValue();
                    var pname = productsview.get(id).productname;
                    var winLabel1 = pcategory + "--" + pname;


                    var productPrices = id;
                    pricechartview.clearAll();
                    pricechartview.attachEvent("onXLS", function () {
                        posLayout.cells("c").progressOn();
                    });
                    pricechartview.attachEvent("onXLE", function () {
                        posLayout.cells("c").progressOff();
                    });
                    pricechartview.load("viewmodel/dataview/com/com/crm/productprices.jsp?productPrices=" + productPrices, "json");
//                       alert(productPrices);

                    //Create The sale Window once the target Unit of Measure is Selected
                    pricechartview.attachEvent("onItemClick", function (id, ev, html) {
                        var uomID = id;
//                    alert(uomID);
                        // var punits = pricechartview.get(id).units;
                        // var pPrice = pricechartview.get(id).price;
                        //var winLabel=winLabel1+" , "+pPrice+" per "+punits;
                        var winLabel = winLabel1;
                        //
                        //createSaleWindow(productPrice, "Add Product Sevice", dhxWins);
                        //   alert(productPrice);
                        var winexist = dhxWins.isWindow("productsale" + uomID);
                        // var quotekey = window.quote;
                        if (winexist == false) {
                            createSaleWindow(posmainTabbar, id, winLabel,posLineGrid);
                        } else {
                            //window(id).close();
                            //dhxWins.window("productsale"+id).show();
                            //dhxWins.window("productsale"+id).bringToTop()
                            dhxWins.window("productsale" + uomID).close();
                            createSaleWindow(posmainTabbar, id, winLabel,posLineGrid);
                        }
                    });

                });

            });

//alert(productPrice);


//setting object properties
            productclassview.load('viewmodel/dataview/com/com/crm/productclass.jsp', 'json');
            //productsview.load('viewmodel/dataview/com/com/crm/products.jsp', 'json');
            //pricechartview.load('viewmodel/dataview/com/com/crm/productprices.jsp', 'json');

            //object events
            productclassview.attachEvent("onItemClick", function (id, ev, html) {
                var productClass = id;

                productclassviewOnselect(productClass, categoryGrid);
                return true;
            });
            function productclassviewOnselect(productClass, categoryGrid) {
                categoryGrid.clearAll();
                categoryGrid.load("viewmodel/grid/com/com/crm/posproductcategory.jsp?productClassId=" + productClass, "json");
                return productClass;
            }
            var customersposForm = createCustomersPosform(salesLayout, -1);


            function createCustomersPosform(salesLayout, rId) {

                var customersposForm = salesLayout.cells("a").attachForm();
                // alert("./viewmodel/form/com/com/crm/customerspos.jsp?id="+rId);
                salesLayout.cells("a").progressOn();
                customersposForm.loadStruct("./viewmodel/form/com/com/crm/customerspos.jsp?id=" + rId, function () {
                    salesLayout.cells("a").progressOff();
                });
                customersposForm.enableLiveValidation(true);
                customersposForm.attachEvent("onButtonClick", function (id) {
                    credentialsFormOnclick(id, customersposForm, salesLayout);
                });

                return customersposForm;
            }




         var posLineGrid = salesLayout.cells("b").attachGrid();
            posLineGrid.setColTypes("ro,ro,ro");
            posLineGrid.setHeader("Product Name,Quantity,Sale Units,Unit Price,Amount");
            posLineGrid.setColAlign("left,left,left,left,left");
            posLineGrid.setInitWidthsP("*,10,15,10,15");
            posLineGrid.attachHeader("#text_filter,#text_filter,#text_filter,#text_filter,#text_filter");
            posLineGrid.setColSorting("str,str,str,str,str");
            posLineGrid.init();
//                    function  createSaleWindow(productPrice, dhxWins) {
//
//                    var saleswin = dhxWins.createWindow("productsale" + productPrice, 150, 30, 800, 500);
//                            saleswin.setText("<b>Product sale Details (Select Product price and Sale units)</b>");
//                    }  createSaleWindow(posmainTabbar, id,winLabel);
            function createSaleWindow(posmainTabbar, itemsaleunitsid, pname) {

                var salewin = dhxWins.createWindow("productsale" + itemsaleunitsid, 250, 10, 1000, 700);
                // var pname=productsview.get(productPrice);

                salewin.setText("<b>" + pname + "</b>");
                //return true;
                var winLayout = salewin.attachLayout({
                    pattern: "1C",
                    cells: [
                        {id: "a", text: "Views", header: false, height: 300},
                    ]
                });
             loadWindowdata(winLayout, itemsaleunitsid,posLineGrid);
                //                var posglassForm = createPosGlassform(winLayout,  rId);

            }
            // var posglassForm = createPosGlassform(winLayout,  rId);

            function loadWindowdata(winLayout, rId,posLineGrid) {

                var posglassForm = winLayout.cells("a").attachForm();
                winLayout.cells("a").progressOn();
//alert ("./viewmodel/form/com/com/crm/posglass.jsp?id=" + rId);
                posglassForm.loadStruct("./viewmodel/form/com/com/crm/posglass.jsp?id=-1&itemsaleunitsid=" + rId, function () {
                    winLayout.cells("a").progressOff();
                });
                //attachURL("./viewmodel/form/com/com/crm/posglass.jsp");
                posglassForm.enableLiveValidation(true);
                posglassForm.attachEvent("onButtonClick", function (id) {
                    posglassFormOnclick(id, posglassForm,posLineGrid);
                    posmainTabbar.cells(salesid).setActive();
                });

                return posglassForm;
            }
        </script>   
        <div id="comcomcrmpos"  style="position:absolute; top:0px;  bottom:10px; left:5px; right:15px; width:99%; height:100%; aborder: #B5CDE4 1px solid;">

    </body>
</html>
